// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advanced.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const freshLowViewEligible = `-- name: FreshLowViewEligible :many
SELECT d.video_id, d.channel_id
FROM search.documents d
WHERE d.eligible
  AND (NOT $1::bool OR NOT d.is_sensitive)
  AND d.views <= $2::bigint
  AND ($3::text IS NULL OR d.language = $3)
ORDER BY d.published_at DESC NULLS LAST, d.video_id
LIMIT $4::int
`

type FreshLowViewEligibleParams struct {
	HideSensitive bool    `json:"hide_sensitive"`
	MaxViews      int64   `json:"max_views"`
	Language      *string `json:"language"`
	Lim           int32   `json:"lim"`
}

type FreshLowViewEligibleRow struct {
	VideoID   uuid.UUID   `json:"video_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

// The ε-greedy exploration pool: fresh, low-view eligible docs, newest first.
func (q *Queries) FreshLowViewEligible(ctx context.Context, arg FreshLowViewEligibleParams) ([]FreshLowViewEligibleRow, error) {
	rows, err := q.db.Query(ctx, freshLowViewEligible,
		arg.HideSensitive,
		arg.MaxViews,
		arg.Language,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FreshLowViewEligibleRow
	for rows.Next() {
		var i FreshLowViewEligibleRow
		if err := rows.Scan(&i.VideoID, &i.ChannelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocFeaturesByIDs = `-- name: ListDocFeaturesByIDs :many
SELECT d.video_id, d.channel_id, d.language, d.category, d.tags,
       d.views, d.published_at, d.source_updated_at
FROM search.documents d
WHERE d.eligible
  AND (NOT $1::bool OR NOT d.is_sensitive)
  AND d.video_id = ANY($2::uuid[])
`

type ListDocFeaturesByIDsParams struct {
	HideSensitive bool        `json:"hide_sensitive"`
	Ids           []uuid.UUID `json:"ids"`
}

type ListDocFeaturesByIDsRow struct {
	VideoID         uuid.UUID          `json:"video_id"`
	ChannelID       pgtype.UUID        `json:"channel_id"`
	Language        *string            `json:"language"`
	Category        *string            `json:"category"`
	Tags            []string           `json:"tags"`
	Views           int64              `json:"views"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	SourceUpdatedAt time.Time          `json:"source_updated_at"`
}

// Rerank features for a candidate id set (advanced related/home): eligible (and,
// when requested, non-sensitive) docs only. Order is not preserved.
func (q *Queries) ListDocFeaturesByIDs(ctx context.Context, arg ListDocFeaturesByIDsParams) ([]ListDocFeaturesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listDocFeaturesByIDs, arg.HideSensitive, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocFeaturesByIDsRow
	for rows.Next() {
		var i ListDocFeaturesByIDsRow
		if err := rows.Scan(
			&i.VideoID,
			&i.ChannelID,
			&i.Language,
			&i.Category,
			&i.Tags,
			&i.Views,
			&i.PublishedAt,
			&i.SourceUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const neighborAffinity = `-- name: NeighborAffinity :many
SELECT n.neighbor_id AS video_id, sum(uwp.weight * n.score)::double precision AS affinity
FROM search.user_watch_projection uwp
JOIN search.item_neighbors n ON n.video_id = uwp.video_id
WHERE uwp.user_id = $1
  AND n.neighbor_id = ANY($2::uuid[])
GROUP BY n.neighbor_id
`

type NeighborAffinityParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Candidates []uuid.UUID `json:"candidates"`
}

type NeighborAffinityRow struct {
	VideoID  uuid.UUID `json:"video_id"`
	Affinity float64   `json:"affinity"`
}

// Per-candidate personal affinity: for each candidate that neighbors a video the
// user has watched, the projection-weighted sum of neighbor scores.
func (q *Queries) NeighborAffinity(ctx context.Context, arg NeighborAffinityParams) ([]NeighborAffinityRow, error) {
	rows, err := q.db.Query(ctx, neighborAffinity, arg.UserID, arg.Candidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NeighborAffinityRow
	for rows.Next() {
		var i NeighborAffinityRow
		if err := rows.Scan(&i.VideoID, &i.Affinity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentlyWatchedVideos = `-- name: RecentlyWatchedVideos :many
SELECT video_id
FROM search.user_watch_projection
WHERE user_id = $1
ORDER BY last_watched_at DESC, video_id
LIMIT $2::int
`

type RecentlyWatchedVideosParams struct {
	UserID uuid.UUID `json:"user_id"`
	Lim    int32     `json:"lim"`
}

// The user's most recently watched videos (novelty demotion / hide-watched).
func (q *Queries) RecentlyWatchedVideos(ctx context.Context, arg RecentlyWatchedVideosParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, recentlyWatchedVideos, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var video_id uuid.UUID
		if err := rows.Scan(&video_id); err != nil {
			return nil, err
		}
		items = append(items, video_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAdvancedRecall = `-- name: SearchAdvancedRecall :many

WITH q AS (
    SELECT websearch_to_tsquery('simple', $1::text) AS tsq
),
recall AS (
    SELECT d.video_id
    FROM search.documents d, q
    WHERE d.eligible
      AND (NOT $6::bool OR NOT d.is_sensitive)
      AND (
            d.tsv @@ q.tsq
         OR similarity(lower(d.title), $1::text) >= 0.3
         OR $1::text = ANY(SELECT lower(x) FROM unnest(d.tags) AS x)
         OR lower(coalesce(d.channel_name, '')) = $1::text
          )
    UNION
    SELECT qve.video_id
    FROM search.query_video_engagement qve
    JOIN search.documents d ON d.video_id = qve.video_id
    WHERE qve.normalized_query = $1::text
      AND qve.clicks > 0
      AND d.eligible
      AND (NOT $6::bool OR NOT d.is_sensitive)
)
SELECT d.video_id, d.channel_id, d.language, d.category, d.tags,
       d.views, d.published_at, d.source_updated_at,
       ts_rank_cd(d.tsv, q.tsq)::double precision AS ts_rank,
       COALESCE(similarity(lower(d.title), $1::text), 0)::double precision AS trgm_sim,
       ( (CASE WHEN lower(d.title) = $1::text THEN 1.0 ELSE 0.0 END)
       + (CASE WHEN lower(coalesce(d.channel_name, '')) = $1::text THEN 0.5 ELSE 0.0 END)
       + (CASE WHEN $1::text = ANY(SELECT lower(x) FROM unnest(d.tags) AS x) THEN 0.5 ELSE 0.0 END)
       )::double precision AS exact_flags,
       COALESCE(qve.impressions, 0)::bigint AS impressions,
       COALESCE(qve.clicks, 0)::bigint AS clicks,
       COALESCE(qve.meaningful_watches, 0)::bigint AS meaningful_watches
FROM search.documents d
CROSS JOIN q
JOIN recall r ON r.video_id = d.video_id
LEFT JOIN search.query_video_engagement qve
       ON qve.normalized_query = $1::text AND qve.video_id = d.video_id
WHERE ($2::text IS NULL OR $2 = ANY(d.tags))
  AND ($3::text IS NULL OR d.category = $3)
  AND ($4::text IS NULL OR d.language = $4)
ORDER BY ts_rank DESC, d.views DESC, d.video_id
LIMIT $5::int
`

type SearchAdvancedRecallParams struct {
	Query         string  `json:"query"`
	Tag           *string `json:"tag"`
	Category      *string `json:"category"`
	Language      *string `json:"language"`
	Lim           int32   `json:"lim"`
	HideSensitive bool    `json:"hide_sensitive"`
}

type SearchAdvancedRecallRow struct {
	VideoID           uuid.UUID          `json:"video_id"`
	ChannelID         pgtype.UUID        `json:"channel_id"`
	Language          *string            `json:"language"`
	Category          *string            `json:"category"`
	Tags              []string           `json:"tags"`
	Views             int64              `json:"views"`
	PublishedAt       pgtype.Timestamptz `json:"published_at"`
	SourceUpdatedAt   time.Time          `json:"source_updated_at"`
	TsRank            float64            `json:"ts_rank"`
	TrgmSim           float64            `json:"trgm_sim"`
	ExactFlags        float64            `json:"exact_flags"`
	Impressions       int64              `json:"impressions"`
	Clicks            int64              `json:"clicks"`
	MeaningfulWatches int64              `json:"meaningful_watches"`
}

// Advanced-mode feature reads (§1.7, §1.8). Stage-1 recall returns rich per-doc
// columns so the Go linear ranker (internal/ranking) can rerank without extra
// round trips; the affinity/session queries supply the personalization features.
// Stage-1 recall for advanced search: the simple-mode hybrid recall (full-text ∪
// trigram title ∪ exact tag/channel) UNION the videos that earned clicks for this
// exact query (query_video_engagement), capped at @lim (500). Each row carries the
// text-match components and the per-(query,video) engagement counters (LEFT
// JOINed) so stage-2 computes text_score + smoothed CTR + meaningful-watch-rate in
// Go. Ordered by text relevance then views so the cap keeps the most relevant.
func (q *Queries) SearchAdvancedRecall(ctx context.Context, arg SearchAdvancedRecallParams) ([]SearchAdvancedRecallRow, error) {
	rows, err := q.db.Query(ctx, searchAdvancedRecall,
		arg.Query,
		arg.Tag,
		arg.Category,
		arg.Language,
		arg.Lim,
		arg.HideSensitive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAdvancedRecallRow
	for rows.Next() {
		var i SearchAdvancedRecallRow
		if err := rows.Scan(
			&i.VideoID,
			&i.ChannelID,
			&i.Language,
			&i.Category,
			&i.Tags,
			&i.Views,
			&i.PublishedAt,
			&i.SourceUpdatedAt,
			&i.TsRank,
			&i.TrgmSim,
			&i.ExactFlags,
			&i.Impressions,
			&i.Clicks,
			&i.MeaningfulWatches,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userChannelAffinity = `-- name: UserChannelAffinity :many
SELECT d.channel_id, sum(uwp.weight)::double precision AS weight
FROM search.user_watch_projection uwp
JOIN search.documents d ON d.video_id = uwp.video_id
WHERE uwp.user_id = $1
  AND d.channel_id IS NOT NULL
GROUP BY d.channel_id
`

type UserChannelAffinityRow struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	Weight    float64     `json:"weight"`
}

// Total decayed watch weight the user has accumulated on each channel — the
// "direct channel affinity" personalization term (and the "subscribed"-style
// reason source, since search has no subscription data).
func (q *Queries) UserChannelAffinity(ctx context.Context, userID uuid.UUID) ([]UserChannelAffinityRow, error) {
	rows, err := q.db.Query(ctx, userChannelAffinity, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserChannelAffinityRow
	for rows.Next() {
		var i UserChannelAffinityRow
		if err := rows.Scan(&i.ChannelID, &i.Weight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
