// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: behavior.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendQueryLog = `-- name: AppendQueryLog :exec
INSERT INTO search.query_log
    (event_id, normalized_query, display_query, user_id, session_id, results_count, submitted_at)
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (event_id) DO NOTHING
`

type AppendQueryLogParams struct {
	EventID         pgtype.UUID `json:"event_id"`
	NormalizedQuery string      `json:"normalized_query"`
	DisplayQuery    string      `json:"display_query"`
	UserID          pgtype.UUID `json:"user_id"`
	SessionID       *string     `json:"session_id"`
	ResultsCount    *int32      `json:"results_count"`
	SubmittedAt     time.Time   `json:"submitted_at"`
}

// One raw query_log row per search.submitted. Deduped on event_id so a replayed
// batch does not double-count. user_id is retained for exact distinct-user
// counting (NULLed on history deletion).
func (q *Queries) AppendQueryLog(ctx context.Context, arg AppendQueryLogParams) error {
	_, err := q.db.Exec(ctx, appendQueryLog,
		arg.EventID,
		arg.NormalizedQuery,
		arg.DisplayQuery,
		arg.UserID,
		arg.SessionID,
		arg.ResultsCount,
		arg.SubmittedAt,
	)
	return err
}

const insertBehaviorEvent = `-- name: InsertBehaviorEvent :exec

INSERT INTO search.behavior_events
    (event_id, type, user_id, session_id, normalized_query, video_id, "position", model_version, occurred_at, props)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (event_id) DO NOTHING
`

type InsertBehaviorEventParams struct {
	EventID         uuid.UUID   `json:"event_id"`
	Type            string      `json:"type"`
	UserID          pgtype.UUID `json:"user_id"`
	SessionID       *string     `json:"session_id"`
	NormalizedQuery *string     `json:"normalized_query"`
	VideoID         pgtype.UUID `json:"video_id"`
	Position        *int32      `json:"position"`
	ModelVersion    *string     `json:"model_version"`
	OccurredAt      time.Time   `json:"occurred_at"`
	Props           []byte      `json:"props"`
}

// Behavioral event intake (W2). These run inside the same POST /events
// transaction as the domain effects; the Redis side effects (session context,
// trending, HLL) are flushed only after that transaction commits.
// Durable copy of one behavioral event. event_id is UNIQUE so a redelivery (or a
// re-derivation with a deterministic id) collapses to one row. props keeps the
// full original payload for the rollup/sessionizer workers.
func (q *Queries) InsertBehaviorEvent(ctx context.Context, arg InsertBehaviorEventParams) error {
	_, err := q.db.Exec(ctx, insertBehaviorEvent,
		arg.EventID,
		arg.Type,
		arg.UserID,
		arg.SessionID,
		arg.NormalizedQuery,
		arg.VideoID,
		arg.Position,
		arg.ModelVersion,
		arg.OccurredAt,
		arg.Props,
	)
	return err
}

const upsertUserSearchHistory = `-- name: UpsertUserSearchHistory :exec
INSERT INTO search.user_search_history
    (user_id, normalized_query, display_query, use_count, last_used_at, hidden)
VALUES ($1, $2, $3, 1, $4, false)
ON CONFLICT (user_id, normalized_query) DO UPDATE SET
    use_count     = search.user_search_history.use_count + 1,
    display_query = EXCLUDED.display_query,
    last_used_at  = GREATEST(search.user_search_history.last_used_at, EXCLUDED.last_used_at),
    hidden        = false
`

type UpsertUserSearchHistoryParams struct {
	UserID          uuid.UUID `json:"user_id"`
	NormalizedQuery string    `json:"normalized_query"`
	DisplayQuery    string    `json:"display_query"`
	LastUsedAt      time.Time `json:"last_used_at"`
}

// Personal search history — written ONLY when the event allows history. A repeat
// search bumps use_count and recency; re-searching a previously hidden query
// un-hides it (it is relevant to the user again).
func (q *Queries) UpsertUserSearchHistory(ctx context.Context, arg UpsertUserSearchHistoryParams) error {
	_, err := q.db.Exec(ctx, upsertUserSearchHistory,
		arg.UserID,
		arg.NormalizedQuery,
		arg.DisplayQuery,
		arg.LastUsedAt,
	)
	return err
}

const upsertWatchProjection = `-- name: UpsertWatchProjection :exec
INSERT INTO search.user_watch_projection (user_id, video_id, weight, last_watched_at)
VALUES ($1, $2, $3::real, now())
ON CONFLICT (user_id, video_id) DO UPDATE SET
    weight = search.user_watch_projection.weight
        * power(2, - GREATEST(0, EXTRACT(EPOCH FROM (now() - search.user_watch_projection.last_watched_at)))
                    / (3600.0 * $4::double precision))::real
        + EXCLUDED.weight,
    last_watched_at = now()
`

type UpsertWatchProjectionParams struct {
	UserID        uuid.UUID `json:"user_id"`
	VideoID       uuid.UUID `json:"video_id"`
	Delta         float32   `json:"delta"`
	HalfLifeHours float64   `json:"half_life_hours"`
}

// Decayed per-(user,video) watch affinity — written ONLY when the event allows
// history. Decay is applied at write time using the stored last_watched_at as the
// reference (equivalent to continuous decay), so there is no O(N) sweep: an old
// weight is decayed to now, then the new delta is added.
func (q *Queries) UpsertWatchProjection(ctx context.Context, arg UpsertWatchProjectionParams) error {
	_, err := q.db.Exec(ctx, upsertWatchProjection,
		arg.UserID,
		arg.VideoID,
		arg.Delta,
		arg.HalfLifeHours,
	)
	return err
}
