// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package sqlcgen

import (
	"context"
)

const listServiceConfig = `-- name: ListServiceConfig :many
SELECT key, value, updated_at FROM search.service_config ORDER BY key
`

func (q *Queries) ListServiceConfig(ctx context.Context) ([]SearchServiceConfig, error) {
	rows, err := q.db.Query(ctx, listServiceConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchServiceConfig
	for rows.Next() {
		var i SearchServiceConfig
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertServiceConfig = `-- name: UpsertServiceConfig :exec
INSERT INTO search.service_config (key, value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type UpsertServiceConfigParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertServiceConfig(ctx context.Context, arg UpsertServiceConfigParams) error {
	_, err := q.db.Exec(ctx, upsertServiceConfig, arg.Key, arg.Value)
	return err
}
