// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: covisitation.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const accumulateCoSearch = `-- name: AccumulateCoSearch :exec
WITH clk AS (
    SELECT id, session_id, normalized_query, video_id, occurred_at
    FROM search.behavior_events
    WHERE type = 'search.result_clicked'
      AND session_id IS NOT NULL
      AND video_id IS NOT NULL
      AND normalized_query IS NOT NULL
),
new_clk AS (
    SELECT id, session_id, normalized_query, video_id, occurred_at FROM clk
    WHERE id > $1 AND id <= $2
),
pairs AS (
    SELECT LEAST(n.video_id, p.video_id)  AS video_a,
           GREATEST(n.video_id, p.video_id) AS video_b,
           count(*)                        AS c
    FROM new_clk n
    JOIN clk p
      ON p.session_id = n.session_id
     AND p.normalized_query = n.normalized_query
     AND p.id < n.id
     AND p.video_id <> n.video_id
     AND abs(EXTRACT(EPOCH FROM (n.occurred_at - p.occurred_at))) <= $3::double precision
    GROUP BY 1, 2
)
INSERT INTO search.co_search (video_a, video_b, count, updated_at)
SELECT video_a, video_b, c, now() FROM pairs
ON CONFLICT (video_a, video_b) DO UPDATE
    SET count = search.co_search.count + EXCLUDED.count, updated_at = now()
`

type AccumulateCoSearchParams struct {
	Cursor        int64   `json:"cursor"`
	Maxid         int64   `json:"maxid"`
	WindowSeconds float64 `json:"window_seconds"`
}

func (q *Queries) AccumulateCoSearch(ctx context.Context, arg AccumulateCoSearchParams) error {
	_, err := q.db.Exec(ctx, accumulateCoSearch, arg.Cursor, arg.Maxid, arg.WindowSeconds)
	return err
}

const accumulateCoWatch = `-- name: AccumulateCoWatch :exec

WITH watch AS (
    SELECT id, session_id, video_id, occurred_at
    FROM search.behavior_events
    WHERE type IN ('video.play_started', 'video.meaningful_watch')
      AND session_id IS NOT NULL
      AND video_id IS NOT NULL
),
new_watch AS (
    SELECT id, session_id, video_id, occurred_at FROM watch
    WHERE id > $1 AND id <= $2
),
pairs AS (
    SELECT LEAST(n.video_id, p.video_id)  AS video_a,
           GREATEST(n.video_id, p.video_id) AS video_b,
           count(*)                        AS c
    FROM new_watch n
    JOIN watch p
      ON p.session_id = n.session_id
     AND p.id < n.id
     AND p.video_id <> n.video_id
     AND abs(EXTRACT(EPOCH FROM (n.occurred_at - p.occurred_at))) <= $3::double precision
    GROUP BY 1, 2
)
INSERT INTO search.co_watch (video_a, video_b, count, updated_at)
SELECT video_a, video_b, c, now() FROM pairs
ON CONFLICT (video_a, video_b) DO UPDATE
    SET count = search.co_watch.count + EXCLUDED.count, updated_at = now()
`

type AccumulateCoWatchParams struct {
	Cursor        int64   `json:"cursor"`
	Maxid         int64   `json:"maxid"`
	WindowSeconds float64 `json:"window_seconds"`
}

// Co-visitation worker (§1.9 covis_rollup) and the served neighbor reads.
//
// AccumulateCoWatch / AccumulateCoSearch are cursor-based, like the other rollup
// workers: each pass folds behavior_events with id in (cursor, maxid] into the
// cumulative co-occurrence counters. The pairing counts each unordered pair
// exactly once: a NEW event is paired only with EARLIER events (p.id < n.id) in
// the same session (co_watch) or same session+query (co_search) inside the time
// window. Because every event lands in exactly one cursor range, and the earlier
// partner is always already durable, the unordered pair {earlier, later} is
// counted once — when the later event is the anchor — so re-running a rolled-back
// batch never double counts.
func (q *Queries) AccumulateCoWatch(ctx context.Context, arg AccumulateCoWatchParams) error {
	_, err := q.db.Exec(ctx, accumulateCoWatch, arg.Cursor, arg.Maxid, arg.WindowSeconds)
	return err
}

const clearCovisNeighbors = `-- name: ClearCovisNeighbors :exec
DELETE FROM search.item_neighbors WHERE model_version = 'covis-v1'
`

// Step 1 of the neighbor rebuild: drop the covis-v1 index so it can be recomputed
// from the current co_* counters (both run in the covis worker's transaction).
func (q *Queries) ClearCovisNeighbors(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearCovisNeighbors)
	return err
}

const neighborScoresFromSeeds = `-- name: NeighborScoresFromSeeds :many
SELECT n.neighbor_id AS video_id, sum(n.score)::double precision AS score
FROM search.item_neighbors n
WHERE n.video_id = ANY($1::uuid[])
  AND n.neighbor_id = ANY($2::uuid[])
GROUP BY n.neighbor_id
`

type NeighborScoresFromSeedsParams struct {
	Seeds      []uuid.UUID `json:"seeds"`
	Candidates []uuid.UUID `json:"candidates"`
}

type NeighborScoresFromSeedsRow struct {
	VideoID uuid.UUID `json:"video_id"`
	Score   float64   `json:"score"`
}

// Summed neighbor score of each candidate that neighbors any of the seed videos
// (session-intent / co-watch candidate scoring). Seeds and candidates are id sets.
func (q *Queries) NeighborScoresFromSeeds(ctx context.Context, arg NeighborScoresFromSeedsParams) ([]NeighborScoresFromSeedsRow, error) {
	rows, err := q.db.Query(ctx, neighborScoresFromSeeds, arg.Seeds, arg.Candidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NeighborScoresFromSeedsRow
	for rows.Next() {
		var i NeighborScoresFromSeedsRow
		if err := rows.Scan(&i.VideoID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const neighborsForSeeds = `-- name: NeighborsForSeeds :many
SELECT n.neighbor_id AS video_id, sum(n.score)::double precision AS score
FROM search.item_neighbors n
WHERE n.video_id = ANY($1::uuid[])
  AND NOT (n.neighbor_id = ANY($1::uuid[]))
GROUP BY n.neighbor_id
ORDER BY score DESC, n.neighbor_id
LIMIT $2::int
`

type NeighborsForSeedsParams struct {
	Seeds []uuid.UUID `json:"seeds"`
	Lim   int32       `json:"lim"`
}

type NeighborsForSeedsRow struct {
	VideoID uuid.UUID `json:"video_id"`
	Score   float64   `json:"score"`
}

// Top neighbor videos of a set of seed videos (advanced home/related candidate
// generation from session recency), summed score across seeds, excluding seeds.
func (q *Queries) NeighborsForSeeds(ctx context.Context, arg NeighborsForSeedsParams) ([]NeighborsForSeedsRow, error) {
	rows, err := q.db.Query(ctx, neighborsForSeeds, arg.Seeds, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NeighborsForSeedsRow
	for rows.Next() {
		var i NeighborsForSeedsRow
		if err := rows.Scan(&i.VideoID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const neighborsForUserWatches = `-- name: NeighborsForUserWatches :many
SELECT n.neighbor_id AS video_id, sum(uwp.weight * n.score)::double precision AS score
FROM search.user_watch_projection uwp
JOIN search.item_neighbors n ON n.video_id = uwp.video_id
WHERE uwp.user_id = $1
  AND NOT (n.neighbor_id IN (SELECT video_id FROM search.user_watch_projection WHERE user_id = $1))
GROUP BY n.neighbor_id
ORDER BY score DESC, n.neighbor_id
LIMIT $2::int
`

type NeighborsForUserWatchesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Lim    int32     `json:"lim"`
}

type NeighborsForUserWatchesRow struct {
	VideoID uuid.UUID `json:"video_id"`
	Score   float64   `json:"score"`
}

// Top neighbor videos of everything the user has watched, weighted by the decayed
// watch-projection weight (advanced home co-watch candidate generation). Excludes
// videos the user has already watched.
func (q *Queries) NeighborsForUserWatches(ctx context.Context, arg NeighborsForUserWatchesParams) ([]NeighborsForUserWatchesRow, error) {
	rows, err := q.db.Query(ctx, neighborsForUserWatches, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NeighborsForUserWatchesRow
	for rows.Next() {
		var i NeighborsForUserWatchesRow
		if err := rows.Scan(&i.VideoID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const neighborsForVideo = `-- name: NeighborsForVideo :many
SELECT neighbor_id, score, source
FROM search.item_neighbors
WHERE video_id = $1
ORDER BY score DESC, neighbor_id
LIMIT $2::int
`

type NeighborsForVideoParams struct {
	VideoID uuid.UUID `json:"video_id"`
	Lim     int32     `json:"lim"`
}

type NeighborsForVideoRow struct {
	NeighborID uuid.UUID `json:"neighbor_id"`
	Score      float32   `json:"score"`
	Source     string    `json:"source"`
}

// Served related candidates for a seed video, best neighbor first.
func (q *Queries) NeighborsForVideo(ctx context.Context, arg NeighborsForVideoParams) ([]NeighborsForVideoRow, error) {
	rows, err := q.db.Query(ctx, neighborsForVideo, arg.VideoID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NeighborsForVideoRow
	for rows.Next() {
		var i NeighborsForVideoRow
		if err := rows.Scan(&i.NeighborID, &i.Score, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildCovisNeighbors = `-- name: RebuildCovisNeighbors :exec
WITH cw AS (
    SELECT video_a AS i, video_b AS j, count::double precision AS c FROM search.co_watch
    UNION ALL
    SELECT video_b AS i, video_a AS j, count::double precision AS c FROM search.co_watch
),
cw_tot AS (SELECT i, sum(c) AS t FROM cw GROUP BY i),
cs AS (
    SELECT video_a AS i, video_b AS j, count::double precision AS c FROM search.co_search
    UNION ALL
    SELECT video_b AS i, video_a AS j, count::double precision AS c FROM search.co_search
),
cs_tot AS (SELECT i, sum(c) AS t FROM cs GROUP BY i),
edges AS (
    SELECT COALESCE(cw.i, cs.i) AS i,
           COALESCE(cw.j, cs.j) AS j,
           ( 0.7 * COALESCE(
                 (cw.c / sqrt(cwti.t * cwtj.t)) * (cw.c / (cw.c + $2::double precision)), 0)
           + 0.3 * COALESCE(
                 (cs.c / sqrt(csti.t * cstj.t)) * (cs.c / (cs.c + $2::double precision)), 0)
           )::real AS score
    FROM cw
    FULL OUTER JOIN cs ON cs.i = cw.i AND cs.j = cw.j
    LEFT JOIN cw_tot cwti ON cwti.i = cw.i
    LEFT JOIN cw_tot cwtj ON cwtj.i = cw.j
    LEFT JOIN cs_tot csti ON csti.i = cs.i
    LEFT JOIN cs_tot cstj ON cstj.i = cs.j
),
ranked AS (
    SELECT i, j, score,
           row_number() OVER (PARTITION BY i ORDER BY score DESC, j) AS rn
    FROM edges
    WHERE score > 0
)
INSERT INTO search.item_neighbors (video_id, neighbor_id, score, source, model_version)
SELECT i, j, score, 'blend', 'covis-v1'
FROM ranked
WHERE rn <= $1::int
`

type RebuildCovisNeighborsParams struct {
	TopM   int32   `json:"top_m"`
	Lambda float64 `json:"lambda"`
}

// Step 2 of the neighbor rebuild. For each ordered direction (i → j) the shrunk
// cosine of a matrix is
//
//	raw    = cooc(i,j) / sqrt(total(i) * total(j))
//	shrunk = raw * cooc(i,j) / (cooc(i,j) + lambda)
//
// where total(i) is i's summed co-occurrence mass in that matrix. The shrinkage
// factor cooc/(cooc+lambda) damps low-support pairs toward zero (algorithms
// report λ≈10). co_watch and co_search are blended 0.7 / 0.3, and the top-M
// neighbors per item (by score, id tie-break) are kept as source='blend'.
func (q *Queries) RebuildCovisNeighbors(ctx context.Context, arg RebuildCovisNeighborsParams) error {
	_, err := q.db.Exec(ctx, rebuildCovisNeighbors, arg.TopM, arg.Lambda)
	return err
}
