// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDocumentsByEligibility = `-- name: CountDocumentsByEligibility :many
SELECT eligible, count(*)::bigint AS count
FROM search.documents
GROUP BY eligible
`

type CountDocumentsByEligibilityRow struct {
	Eligible bool  `json:"eligible"`
	Count    int64 `json:"count"`
}

func (q *Queries) CountDocumentsByEligibility(ctx context.Context) ([]CountDocumentsByEligibilityRow, error) {
	rows, err := q.db.Query(ctx, countDocumentsByEligibility)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDocumentsByEligibilityRow
	for rows.Next() {
		var i CountDocumentsByEligibilityRow
		if err := rows.Scan(&i.Eligible, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocument = `-- name: GetDocument :one
SELECT video_id, kind, channel_id, channel_handle, channel_name, owner_id,
       title, description, tags, category, language, duration_seconds,
       is_sensitive, eligible, suppressed_reason, views, likes,
       published_at, source_updated_at, indexed_at, reconcile_run_id
FROM search.documents
WHERE video_id = $1
`

type GetDocumentRow struct {
	VideoID          uuid.UUID          `json:"video_id"`
	Kind             string             `json:"kind"`
	ChannelID        pgtype.UUID        `json:"channel_id"`
	ChannelHandle    *string            `json:"channel_handle"`
	ChannelName      *string            `json:"channel_name"`
	OwnerID          pgtype.UUID        `json:"owner_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	Tags             []string           `json:"tags"`
	Category         *string            `json:"category"`
	Language         *string            `json:"language"`
	DurationSeconds  *int32             `json:"duration_seconds"`
	IsSensitive      bool               `json:"is_sensitive"`
	Eligible         bool               `json:"eligible"`
	SuppressedReason *string            `json:"suppressed_reason"`
	Views            int64              `json:"views"`
	Likes            int32              `json:"likes"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	SourceUpdatedAt  time.Time          `json:"source_updated_at"`
	IndexedAt        time.Time          `json:"indexed_at"`
	ReconcileRunID   pgtype.UUID        `json:"reconcile_run_id"`
}

func (q *Queries) GetDocument(ctx context.Context, videoID uuid.UUID) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, videoID)
	var i GetDocumentRow
	err := row.Scan(
		&i.VideoID,
		&i.Kind,
		&i.ChannelID,
		&i.ChannelHandle,
		&i.ChannelName,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Category,
		&i.Language,
		&i.DurationSeconds,
		&i.IsSensitive,
		&i.Eligible,
		&i.SuppressedReason,
		&i.Views,
		&i.Likes,
		&i.PublishedAt,
		&i.SourceUpdatedAt,
		&i.IndexedAt,
		&i.ReconcileRunID,
	)
	return i, err
}

const restoreOwnerDocuments = `-- name: RestoreOwnerDocuments :exec
UPDATE search.documents
SET eligible = true, suppressed_reason = NULL, indexed_at = now()
WHERE owner_id = $1 AND suppressed_reason = $2
`

type RestoreOwnerDocumentsParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Reason  *string     `json:"reason"`
}

// user.suppress with unlisted=false: undo ONLY the owner-unlisted suppression.
// Documents hidden for another reason (deleted, blocked, private) stay hidden —
// we cannot re-derive their true eligibility without the source privacy/state.
func (q *Queries) RestoreOwnerDocuments(ctx context.Context, arg RestoreOwnerDocumentsParams) error {
	_, err := q.db.Exec(ctx, restoreOwnerDocuments, arg.OwnerID, arg.Reason)
	return err
}

const suppressChannelDocuments = `-- name: SuppressChannelDocuments :exec
UPDATE search.documents
SET eligible = false, suppressed_reason = $1, indexed_at = now()
WHERE channel_id = $2
`

type SuppressChannelDocumentsParams struct {
	Reason    *string     `json:"reason"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

func (q *Queries) SuppressChannelDocuments(ctx context.Context, arg SuppressChannelDocumentsParams) error {
	_, err := q.db.Exec(ctx, suppressChannelDocuments, arg.Reason, arg.ChannelID)
	return err
}

const suppressDocument = `-- name: SuppressDocument :exec
INSERT INTO search.documents (video_id, title, source_updated_at, eligible, suppressed_reason)
VALUES ($1, '', now(), false, $2)
ON CONFLICT (video_id) DO UPDATE SET
    eligible          = false,
    suppressed_reason = $2,
    indexed_at        = now()
`

type SuppressDocumentParams struct {
	VideoID uuid.UUID `json:"video_id"`
	Reason  *string   `json:"reason"`
}

// Hard visibility kill for a single video (video.suppress). Idempotent: a row
// that does not exist yet is inserted as an ineligible placeholder so a suppress
// that races ahead of the upsert still hides the video once it arrives.
func (q *Queries) SuppressDocument(ctx context.Context, arg SuppressDocumentParams) error {
	_, err := q.db.Exec(ctx, suppressDocument, arg.VideoID, arg.Reason)
	return err
}

const suppressOwnerDocuments = `-- name: SuppressOwnerDocuments :exec
UPDATE search.documents
SET eligible = false, suppressed_reason = $1, indexed_at = now()
WHERE owner_id = $2 AND eligible
`

type SuppressOwnerDocumentsParams struct {
	Reason  *string     `json:"reason"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

// user.suppress with unlisted=true: hide the owner's currently-VISIBLE documents.
// The `AND eligible` guard is essential: without it this would stamp
// suppressed_reason='owner_unlisted' onto docs already hidden for another reason
// (deleted/blocked/private), and RestoreOwnerDocuments would then wrongly
// re-enable them on relist. Only docs this stamp actually hid are later restored.
func (q *Queries) SuppressOwnerDocuments(ctx context.Context, arg SuppressOwnerDocumentsParams) error {
	_, err := q.db.Exec(ctx, suppressOwnerDocuments, arg.Reason, arg.OwnerID)
	return err
}

const suppressReconcileOrphans = `-- name: SuppressReconcileOrphans :exec
UPDATE search.documents
SET eligible = false, suppressed_reason = 'reconcile_orphan', indexed_at = now()
WHERE kind = 'local'
  AND eligible
  AND reconcile_run_id IS DISTINCT FROM $1
`

// After reconcile.end: hide eligible LOCAL documents the current run never
// stamped — they no longer exist (or are no longer public) at the source.
func (q *Queries) SuppressReconcileOrphans(ctx context.Context, reconcileRunID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, suppressReconcileOrphans, reconcileRunID)
	return err
}

const updateChannelDocuments = `-- name: UpdateChannelDocuments :exec
UPDATE search.documents
SET channel_handle = $1,
    channel_name   = $2,
    owner_id       = $3,
    indexed_at     = now()
WHERE channel_id = $4
`

type UpdateChannelDocumentsParams struct {
	ChannelHandle *string     `json:"channel_handle"`
	ChannelName   *string     `json:"channel_name"`
	OwnerID       pgtype.UUID `json:"owner_id"`
	ChannelID     pgtype.UUID `json:"channel_id"`
}

// Denormalize a channel.upsert onto every document owned by that channel.
func (q *Queries) UpdateChannelDocuments(ctx context.Context, arg UpdateChannelDocumentsParams) error {
	_, err := q.db.Exec(ctx, updateChannelDocuments,
		arg.ChannelHandle,
		arg.ChannelName,
		arg.OwnerID,
		arg.ChannelID,
	)
	return err
}

const updateDocumentStats = `-- name: UpdateDocumentStats :exec
UPDATE search.documents
SET views = $1, likes = $2, indexed_at = now()
WHERE video_id = $3
`

type UpdateDocumentStatsParams struct {
	Views   int64     `json:"views"`
	Likes   int32     `json:"likes"`
	VideoID uuid.UUID `json:"video_id"`
}

func (q *Queries) UpdateDocumentStats(ctx context.Context, arg UpdateDocumentStatsParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStats, arg.Views, arg.Likes, arg.VideoID)
	return err
}

const upsertDocument = `-- name: UpsertDocument :exec
INSERT INTO search.documents (
    video_id, kind, channel_id, channel_handle, channel_name, owner_id,
    title, description, tags, category, language, duration_seconds,
    is_sensitive, eligible, suppressed_reason, views, likes,
    published_at, source_updated_at, indexed_at, reconcile_run_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17,
    $18, $19, now(), $20
)
ON CONFLICT (video_id) DO UPDATE SET
    kind              = EXCLUDED.kind,
    channel_id        = EXCLUDED.channel_id,
    channel_handle    = EXCLUDED.channel_handle,
    channel_name      = EXCLUDED.channel_name,
    owner_id          = EXCLUDED.owner_id,
    title             = EXCLUDED.title,
    description       = EXCLUDED.description,
    tags              = EXCLUDED.tags,
    category          = EXCLUDED.category,
    language          = EXCLUDED.language,
    duration_seconds  = EXCLUDED.duration_seconds,
    is_sensitive      = EXCLUDED.is_sensitive,
    eligible          = EXCLUDED.eligible,
    suppressed_reason = EXCLUDED.suppressed_reason,
    views             = EXCLUDED.views,
    likes             = EXCLUDED.likes,
    published_at      = EXCLUDED.published_at,
    source_updated_at = EXCLUDED.source_updated_at,
    indexed_at        = now(),
    reconcile_run_id  = COALESCE(EXCLUDED.reconcile_run_id, search.documents.reconcile_run_id)
`

type UpsertDocumentParams struct {
	VideoID          uuid.UUID          `json:"video_id"`
	Kind             string             `json:"kind"`
	ChannelID        pgtype.UUID        `json:"channel_id"`
	ChannelHandle    *string            `json:"channel_handle"`
	ChannelName      *string            `json:"channel_name"`
	OwnerID          pgtype.UUID        `json:"owner_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	Tags             []string           `json:"tags"`
	Category         *string            `json:"category"`
	Language         *string            `json:"language"`
	DurationSeconds  *int32             `json:"duration_seconds"`
	IsSensitive      bool               `json:"is_sensitive"`
	Eligible         bool               `json:"eligible"`
	SuppressedReason *string            `json:"suppressed_reason"`
	Views            int64              `json:"views"`
	Likes            int32              `json:"likes"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	SourceUpdatedAt  time.Time          `json:"source_updated_at"`
	ReconcileRunID   pgtype.UUID        `json:"reconcile_run_id"`
}

// Insert or refresh a document from a video.upsert (or reconcile.page) event.
// eligible + suppressed_reason are derived in Go from privacy/state. On a
// reconcile page the caller passes reconcile_run_id to stamp the row; on a
// normal upsert it passes NULL and the existing stamp is preserved (COALESCE),
// so a later reconcile.end only suppresses rows the current run never touched.
func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error {
	_, err := q.db.Exec(ctx, upsertDocument,
		arg.VideoID,
		arg.Kind,
		arg.ChannelID,
		arg.ChannelHandle,
		arg.ChannelName,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.Category,
		arg.Language,
		arg.DurationSeconds,
		arg.IsSensitive,
		arg.Eligible,
		arg.SuppressedReason,
		arg.Views,
		arg.Likes,
		arg.PublishedAt,
		arg.SourceUpdatedAt,
		arg.ReconcileRunID,
	)
	return err
}
