// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertInboxEvent = `-- name: InsertInboxEvent :one
INSERT INTO search.events_inbox (event_id, type)
VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
RETURNING event_id
`

type InsertInboxEventParams struct {
	EventID uuid.UUID `json:"event_id"`
	Type    string    `json:"type"`
}

// Record an event id in the dedupe ledger. Returns the row only on a fresh
// insert; a conflict (redelivery) returns no rows, which the caller reads as a
// duplicate and skips the event's side effects.
func (q *Queries) InsertInboxEvent(ctx context.Context, arg InsertInboxEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertInboxEvent, arg.EventID, arg.Type)
	var event_id uuid.UUID
	err := row.Scan(&event_id)
	return event_id, err
}
