// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const anonymizeBehaviorEventsUser = `-- name: AnonymizeBehaviorEventsUser :exec
UPDATE search.behavior_events SET user_id = NULL WHERE user_id = $1
`

func (q *Queries) AnonymizeBehaviorEventsUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, anonymizeBehaviorEventsUser, userID)
	return err
}

const anonymizeQueryLogUser = `-- name: AnonymizeQueryLogUser :exec
UPDATE search.query_log SET user_id = NULL WHERE user_id = $1
`

func (q *Queries) AnonymizeQueryLogUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, anonymizeQueryLogUser, userID)
	return err
}

const deleteUserSearchHistory = `-- name: DeleteUserSearchHistory :exec
DELETE FROM search.user_search_history WHERE user_id = $1
`

func (q *Queries) DeleteUserSearchHistory(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSearchHistory, userID)
	return err
}

const deleteUserSearchHistoryEntry = `-- name: DeleteUserSearchHistoryEntry :exec
DELETE FROM search.user_search_history
WHERE user_id = $1 AND normalized_query = $2
`

type DeleteUserSearchHistoryEntryParams struct {
	UserID          uuid.UUID `json:"user_id"`
	NormalizedQuery string    `json:"normalized_query"`
}

func (q *Queries) DeleteUserSearchHistoryEntry(ctx context.Context, arg DeleteUserSearchHistoryEntryParams) error {
	_, err := q.db.Exec(ctx, deleteUserSearchHistoryEntry, arg.UserID, arg.NormalizedQuery)
	return err
}

const listUserSearchHistory = `-- name: ListUserSearchHistory :many

SELECT normalized_query, display_query, use_count, last_used_at
FROM search.user_search_history
WHERE user_id = $1 AND NOT hidden
ORDER BY last_used_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListUserSearchHistoryParams struct {
	UserID uuid.UUID `json:"user_id"`
	Off    int32     `json:"off"`
	Lim    int32     `json:"lim"`
}

type ListUserSearchHistoryRow struct {
	NormalizedQuery string    `json:"normalized_query"`
	DisplayQuery    string    `json:"display_query"`
	UseCount        int32     `json:"use_count"`
	LastUsedAt      time.Time `json:"last_used_at"`
}

// Privacy / history queries (W2). Back the GET/DELETE user history endpoints and
// the user.history_deleted event handler. Deleting personal history NULLs the
// user_id in the raw logs (anonymization) rather than deleting the rows, so global
// aggregates stay intact while the data no longer references the user.
func (q *Queries) ListUserSearchHistory(ctx context.Context, arg ListUserSearchHistoryParams) ([]ListUserSearchHistoryRow, error) {
	rows, err := q.db.Query(ctx, listUserSearchHistory, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSearchHistoryRow
	for rows.Next() {
		var i ListUserSearchHistoryRow
		if err := rows.Scan(
			&i.NormalizedQuery,
			&i.DisplayQuery,
			&i.UseCount,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeUserWatchProjection = `-- name: PurgeUserWatchProjection :exec
DELETE FROM search.user_watch_projection WHERE user_id = $1
`

func (q *Queries) PurgeUserWatchProjection(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, purgeUserWatchProjection, userID)
	return err
}
