// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SearchBehaviorEvent struct {
	ID              int64       `json:"id"`
	EventID         uuid.UUID   `json:"event_id"`
	Type            string      `json:"type"`
	UserID          pgtype.UUID `json:"user_id"`
	SessionID       *string     `json:"session_id"`
	NormalizedQuery *string     `json:"normalized_query"`
	VideoID         pgtype.UUID `json:"video_id"`
	Position        *int32      `json:"position"`
	ModelVersion    *string     `json:"model_version"`
	OccurredAt      time.Time   `json:"occurred_at"`
	Props           []byte      `json:"props"`
}

type SearchDocument struct {
	VideoID          uuid.UUID          `json:"video_id"`
	Kind             string             `json:"kind"`
	ChannelID        pgtype.UUID        `json:"channel_id"`
	ChannelHandle    *string            `json:"channel_handle"`
	ChannelName      *string            `json:"channel_name"`
	OwnerID          pgtype.UUID        `json:"owner_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	Tags             []string           `json:"tags"`
	Category         *string            `json:"category"`
	Language         *string            `json:"language"`
	DurationSeconds  *int32             `json:"duration_seconds"`
	IsSensitive      bool               `json:"is_sensitive"`
	Eligible         bool               `json:"eligible"`
	SuppressedReason *string            `json:"suppressed_reason"`
	Views            int64              `json:"views"`
	Likes            int32              `json:"likes"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	SourceUpdatedAt  time.Time          `json:"source_updated_at"`
	IndexedAt        time.Time          `json:"indexed_at"`
	ReconcileRunID   pgtype.UUID        `json:"reconcile_run_id"`
	Tsv              interface{}        `json:"tsv"`
}

type SearchEventsInbox struct {
	EventID    uuid.UUID `json:"event_id"`
	Type       string    `json:"type"`
	ReceivedAt time.Time `json:"received_at"`
}

type SearchQueryAggregate struct {
	NormalizedQuery string    `json:"normalized_query"`
	DisplayQuery    string    `json:"display_query"`
	TotalCount      int64     `json:"total_count"`
	DistinctUsers   int32     `json:"distinct_users"`
	DecayedFreq     float64   `json:"decayed_freq"`
	FirstSeen       time.Time `json:"first_seen"`
	LastSeen        time.Time `json:"last_seen"`
	Suggestible     bool      `json:"suggestible"`
	Banned          bool      `json:"banned"`
}

type SearchQueryLog struct {
	ID              int64       `json:"id"`
	EventID         pgtype.UUID `json:"event_id"`
	NormalizedQuery string      `json:"normalized_query"`
	DisplayQuery    string      `json:"display_query"`
	UserID          pgtype.UUID `json:"user_id"`
	SessionID       *string     `json:"session_id"`
	ResultsCount    *int32      `json:"results_count"`
	SubmittedAt     time.Time   `json:"submitted_at"`
}

type SearchQueryVideoEngagement struct {
	NormalizedQuery   string    `json:"normalized_query"`
	VideoID           uuid.UUID `json:"video_id"`
	Impressions       int64     `json:"impressions"`
	Clicks            int64     `json:"clicks"`
	MeaningfulWatches int64     `json:"meaningful_watches"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type SearchServiceConfig struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SearchUserSearchHistory struct {
	UserID          uuid.UUID `json:"user_id"`
	NormalizedQuery string    `json:"normalized_query"`
	DisplayQuery    string    `json:"display_query"`
	UseCount        int32     `json:"use_count"`
	LastUsedAt      time.Time `json:"last_used_at"`
	Hidden          bool      `json:"hidden"`
}

type SearchUserWatchProjection struct {
	UserID        uuid.UUID `json:"user_id"`
	VideoID       uuid.UUID `json:"video_id"`
	Weight        float32   `json:"weight"`
	LastWatchedAt time.Time `json:"last_watched_at"`
}

type SearchWorkerCursor struct {
	CursorName string    `json:"cursor_name"`
	CursorPos  int64     `json:"cursor_pos"`
	UpdatedAt  time.Time `json:"updated_at"`
}
