// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package sqlcgen

import (
	"context"
)

const activateModel = `-- name: ActivateModel :exec
UPDATE search.models
SET status = 'active', activated_at = now()
WHERE kind = $1 AND version = $2
`

type ActivateModelParams struct {
	Kind    string `json:"kind"`
	Version string `json:"version"`
}

// Promote a specific version to active (activation step 2).
func (q *Queries) ActivateModel(ctx context.Context, arg ActivateModelParams) error {
	_, err := q.db.Exec(ctx, activateModel, arg.Kind, arg.Version)
	return err
}

const getActiveModel = `-- name: GetActiveModel :one

SELECT id, kind, version, status, artifact_sha256, artifact_path, metrics, trained_at, activated_at
FROM search.models
WHERE kind = $1 AND status = 'active'
ORDER BY activated_at DESC NULLS LAST, id DESC
LIMIT 1
`

// Model registry (§1.9). Python training INSERTs shadow rows; the Go model_loader
// reads the active ranker, the shadow-eval worker reads shadow rankers and writes
// metrics, and activation flips status (retire previous, activate target).
// The currently-served model of a kind, if any.
func (q *Queries) GetActiveModel(ctx context.Context, kind string) (SearchModel, error) {
	row := q.db.QueryRow(ctx, getActiveModel, kind)
	var i SearchModel
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Version,
		&i.Status,
		&i.ArtifactSha256,
		&i.ArtifactPath,
		&i.Metrics,
		&i.TrainedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const getModelByVersion = `-- name: GetModelByVersion :one
SELECT id, kind, version, status, artifact_sha256, artifact_path, metrics, trained_at, activated_at
FROM search.models
WHERE kind = $1 AND version = $2
`

type GetModelByVersionParams struct {
	Kind    string `json:"kind"`
	Version string `json:"version"`
}

func (q *Queries) GetModelByVersion(ctx context.Context, arg GetModelByVersionParams) (SearchModel, error) {
	row := q.db.QueryRow(ctx, getModelByVersion, arg.Kind, arg.Version)
	var i SearchModel
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Version,
		&i.Status,
		&i.ArtifactSha256,
		&i.ArtifactPath,
		&i.Metrics,
		&i.TrainedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const insertModel = `-- name: InsertModel :one
INSERT INTO search.models (kind, version, status, artifact_sha256, artifact_path, metrics, trained_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (kind, version) DO UPDATE
    SET status = EXCLUDED.status,
        artifact_sha256 = EXCLUDED.artifact_sha256,
        artifact_path = EXCLUDED.artifact_path,
        metrics = EXCLUDED.metrics,
        trained_at = now()
RETURNING id
`

type InsertModelParams struct {
	Kind           string  `json:"kind"`
	Version        string  `json:"version"`
	Status         string  `json:"status"`
	ArtifactSha256 *string `json:"artifact_sha256"`
	ArtifactPath   *string `json:"artifact_path"`
	Metrics        []byte  `json:"metrics"`
}

// Register a freshly-trained artifact (used by Go tests; Python training inserts
// the same shape directly via psycopg).
func (q *Queries) InsertModel(ctx context.Context, arg InsertModelParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertModel,
		arg.Kind,
		arg.Version,
		arg.Status,
		arg.ArtifactSha256,
		arg.ArtifactPath,
		arg.Metrics,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listModels = `-- name: ListModels :many
SELECT id, kind, version, status, artifact_sha256, artifact_path, metrics, trained_at, activated_at
FROM search.models
ORDER BY kind, trained_at DESC, id DESC
`

func (q *Queries) ListModels(ctx context.Context) ([]SearchModel, error) {
	rows, err := q.db.Query(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchModel
	for rows.Next() {
		var i SearchModel
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Status,
			&i.ArtifactSha256,
			&i.ArtifactPath,
			&i.Metrics,
			&i.TrainedAt,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShadowModels = `-- name: ListShadowModels :many
SELECT id, kind, version, status, artifact_sha256, artifact_path, metrics, trained_at, activated_at
FROM search.models
WHERE kind = $1 AND status = 'shadow'
ORDER BY trained_at DESC, id DESC
`

// Shadow models of a kind awaiting evaluation, newest first.
func (q *Queries) ListShadowModels(ctx context.Context, kind string) ([]SearchModel, error) {
	rows, err := q.db.Query(ctx, listShadowModels, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchModel
	for rows.Next() {
		var i SearchModel
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Status,
			&i.ArtifactSha256,
			&i.ArtifactPath,
			&i.Metrics,
			&i.TrainedAt,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireActiveModels = `-- name: RetireActiveModels :exec
UPDATE search.models
SET status = 'retired'
WHERE kind = $1 AND status = 'active'
`

// Retire the currently-active model(s) of a kind (activation step 1).
func (q *Queries) RetireActiveModels(ctx context.Context, kind string) error {
	_, err := q.db.Exec(ctx, retireActiveModels, kind)
	return err
}

const updateModelMetrics = `-- name: UpdateModelMetrics :exec
UPDATE search.models SET metrics = $1 WHERE id = $2
`

type UpdateModelMetricsParams struct {
	Metrics []byte `json:"metrics"`
	ID      int64  `json:"id"`
}

// Record shadow-evaluation metrics onto a model row.
func (q *Queries) UpdateModelMetrics(ctx context.Context, arg UpdateModelMetricsParams) error {
	_, err := q.db.Exec(ctx, updateModelMetrics, arg.Metrics, arg.ID)
	return err
}
