// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SearchDocument struct {
	VideoID          uuid.UUID          `json:"video_id"`
	Kind             string             `json:"kind"`
	ChannelID        pgtype.UUID        `json:"channel_id"`
	ChannelHandle    *string            `json:"channel_handle"`
	ChannelName      *string            `json:"channel_name"`
	OwnerID          pgtype.UUID        `json:"owner_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	Tags             []string           `json:"tags"`
	Category         *string            `json:"category"`
	Language         *string            `json:"language"`
	DurationSeconds  *int32             `json:"duration_seconds"`
	IsSensitive      bool               `json:"is_sensitive"`
	Eligible         bool               `json:"eligible"`
	SuppressedReason *string            `json:"suppressed_reason"`
	Views            int64              `json:"views"`
	Likes            int32              `json:"likes"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	SourceUpdatedAt  time.Time          `json:"source_updated_at"`
	IndexedAt        time.Time          `json:"indexed_at"`
	ReconcileRunID   pgtype.UUID        `json:"reconcile_run_id"`
	Tsv              interface{}        `json:"tsv"`
}

type SearchEventsInbox struct {
	EventID    uuid.UUID `json:"event_id"`
	Type       string    `json:"type"`
	ReceivedAt time.Time `json:"received_at"`
}

type SearchServiceConfig struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}
