// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SearchBehaviorEvent struct {
	ID              int64       `json:"id"`
	EventID         uuid.UUID   `json:"event_id"`
	Type            string      `json:"type"`
	UserID          pgtype.UUID `json:"user_id"`
	SessionID       *string     `json:"session_id"`
	NormalizedQuery *string     `json:"normalized_query"`
	VideoID         pgtype.UUID `json:"video_id"`
	Position        *int32      `json:"position"`
	ModelVersion    *string     `json:"model_version"`
	OccurredAt      time.Time   `json:"occurred_at"`
	Props           []byte      `json:"props"`
}

// RETIRED (0017): no longer read or written. See search.co_watch -- same story for the co-search half of the blend.
type SearchCoSearch struct {
	VideoA    uuid.UUID `json:"video_a"`
	VideoB    uuid.UUID `json:"video_b"`
	Count     int64     `json:"count"`
	UpdatedAt time.Time `json:"updated_at"`
}

// RETIRED (0017): no longer read or written. Co-visitation counts are recomputed from the retained search.behavior_events ledger each covis_rollup pass, because these cumulative counters were never pruned and outlived the events they came from. Kept only so the previous release can still run against this schema; dropped in the next release.
type SearchCoWatch struct {
	VideoA    uuid.UUID `json:"video_a"`
	VideoB    uuid.UUID `json:"video_b"`
	Count     int64     `json:"count"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SearchDocument struct {
	VideoID          uuid.UUID          `json:"video_id"`
	Kind             string             `json:"kind"`
	ChannelID        pgtype.UUID        `json:"channel_id"`
	ChannelHandle    *string            `json:"channel_handle"`
	ChannelName      *string            `json:"channel_name"`
	OwnerID          pgtype.UUID        `json:"owner_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	Tags             []string           `json:"tags"`
	Category         *string            `json:"category"`
	Language         *string            `json:"language"`
	DurationSeconds  *int32             `json:"duration_seconds"`
	IsSensitive      bool               `json:"is_sensitive"`
	Eligible         bool               `json:"eligible"`
	SuppressedReason *string            `json:"suppressed_reason"`
	Views            int64              `json:"views"`
	Likes            int32              `json:"likes"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	SourceUpdatedAt  time.Time          `json:"source_updated_at"`
	IndexedAt        time.Time          `json:"indexed_at"`
	ReconcileRunID   pgtype.UUID        `json:"reconcile_run_id"`
	Tsv              interface{}        `json:"tsv"`
	License          *string            `json:"license"`
}

type SearchEventsInbox struct {
	EventID    uuid.UUID `json:"event_id"`
	Type       string    `json:"type"`
	ReceivedAt time.Time `json:"received_at"`
}

type SearchExperiment struct {
	Key         string    `json:"key"`
	Description string    `json:"description"`
	Variants    []byte    `json:"variants"`
	Salt        string    `json:"salt"`
	Enabled     bool      `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
}

type SearchItemNeighbor struct {
	VideoID      uuid.UUID `json:"video_id"`
	NeighborID   uuid.UUID `json:"neighbor_id"`
	Score        float32   `json:"score"`
	Source       string    `json:"source"`
	ModelVersion string    `json:"model_version"`
}

type SearchModel struct {
	ID             int64              `json:"id"`
	Kind           string             `json:"kind"`
	Version        string             `json:"version"`
	Status         string             `json:"status"`
	ArtifactSha256 *string            `json:"artifact_sha256"`
	ArtifactPath   *string            `json:"artifact_path"`
	Metrics        []byte             `json:"metrics"`
	TrainedAt      time.Time          `json:"trained_at"`
	ActivatedAt    pgtype.Timestamptz `json:"activated_at"`
}

type SearchQueryAggregate struct {
	NormalizedQuery string `json:"normalized_query"`
	DisplayQuery    string `json:"display_query"`
	// Searches for this query the instance STILL HOLDS inside EVENT_RETENTION_DAYS, recomputed from search.query_log by the rollup (queries with new traffic) and by suggestible_reeval (every row, daily). Not cumulative -- migration 0006's decay-then-increment description is superseded.
	TotalCount    int64 `json:"total_count"`
	DistinctUsers int32 `json:"distinct_users"`
	// Recency-weighted popularity and the ORDER of the aggregate autosuggest stream: sum over the RETAINED query_log rows of 2^(-age/half-life), anchored on this query's own last_seen, at SEARCH_QUERY_HALF_LIFE_HOURS. Recomputed, not accumulated, so searches this instance has deleted cannot keep buying a completion its rank.
	DecayedFreq float64   `json:"decayed_freq"`
	FirstSeen   time.Time `json:"first_seen"`
	LastSeen    time.Time `json:"last_seen"`
	Suggestible bool      `json:"suggestible"`
	Banned      bool      `json:"banned"`
}

type SearchQueryLog struct {
	ID              int64       `json:"id"`
	EventID         pgtype.UUID `json:"event_id"`
	NormalizedQuery string      `json:"normalized_query"`
	DisplayQuery    string      `json:"display_query"`
	UserID          pgtype.UUID `json:"user_id"`
	SessionID       *string     `json:"session_id"`
	ResultsCount    *int32      `json:"results_count"`
	SubmittedAt     time.Time   `json:"submitted_at"`
	SubjectID       *string     `json:"subject_id"`
}

// Per-(query, video) engagement counters, RECOMPUTED from the retained search.behavior_events on every engagement_rollup pass (clear + rebuild, no cursor). NOT cumulative -- migration 0009's description of a cursor fold is superseded. Read live: SearchAdvancedRecall recalls candidates on clicks > 0 and feeds impressions/clicks/meaningful_watches into the stage-2 CTR and meaningful-watch-rate features, so a counter that outlived its evidence kept a deleted click ranking a video.
type SearchQueryVideoEngagement struct {
	NormalizedQuery   string    `json:"normalized_query"`
	VideoID           uuid.UUID `json:"video_id"`
	Impressions       int64     `json:"impressions"`
	Clicks            int64     `json:"clicks"`
	MeaningfulWatches int64     `json:"meaningful_watches"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type SearchServiceConfig struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SearchUserSearchHistory struct {
	UserID          uuid.UUID `json:"user_id"`
	NormalizedQuery string    `json:"normalized_query"`
	DisplayQuery    string    `json:"display_query"`
	UseCount        int32     `json:"use_count"`
	LastUsedAt      time.Time `json:"last_used_at"`
	Hidden          bool      `json:"hidden"`
}

type SearchUserWatchProjection struct {
	UserID        uuid.UUID `json:"user_id"`
	VideoID       uuid.UUID `json:"video_id"`
	Weight        float32   `json:"weight"`
	LastWatchedAt time.Time `json:"last_watched_at"`
}

type SearchWorkerCursor struct {
	CursorName string    `json:"cursor_name"`
	CursorPos  int64     `json:"cursor_pos"`
	UpdatedAt  time.Time `json:"updated_at"`
}
