// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommendations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const homeRecent = `-- name: HomeRecent :many
SELECT d.video_id, d.channel_id
FROM search.documents d
WHERE d.eligible
  AND (NOT $1::bool OR NOT d.is_sensitive)
  AND ($2::uuid[] IS NULL OR d.video_id <> ALL($2::uuid[]))
ORDER BY ($3::text IS NOT NULL AND d.language = $3) DESC,
         d.published_at DESC NULLS LAST, d.video_id
LIMIT $4::int
`

type HomeRecentParams struct {
	HideSensitive bool        `json:"hide_sensitive"`
	Exclude       []uuid.UUID `json:"exclude"`
	Language      *string     `json:"language"`
	Lim           int32       `json:"lim"`
}

type HomeRecentRow struct {
	VideoID   uuid.UUID   `json:"video_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

// Freshest eligible videos, same-language preferred first.
func (q *Queries) HomeRecent(ctx context.Context, arg HomeRecentParams) ([]HomeRecentRow, error) {
	rows, err := q.db.Query(ctx, homeRecent,
		arg.HideSensitive,
		arg.Exclude,
		arg.Language,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeRecentRow
	for rows.Next() {
		var i HomeRecentRow
		if err := rows.Scan(&i.VideoID, &i.ChannelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const homeTrending = `-- name: HomeTrending :many
SELECT d.video_id, d.channel_id,
    ( d.views / power(EXTRACT(EPOCH FROM (now() - COALESCE(d.published_at, d.source_updated_at))) / 3600.0 + 2, 1.5) )::double precision AS score
FROM search.documents d
WHERE d.eligible
  AND (NOT $1::bool OR NOT d.is_sensitive)
  AND ($2::uuid[] IS NULL OR d.video_id <> ALL($2::uuid[]))
ORDER BY ($3::text IS NOT NULL AND d.language = $3) DESC,
         score DESC, d.video_id
LIMIT $4::int
`

type HomeTrendingParams struct {
	HideSensitive bool        `json:"hide_sensitive"`
	Exclude       []uuid.UUID `json:"exclude"`
	Language      *string     `json:"language"`
	Lim           int32       `json:"lim"`
}

type HomeTrendingRow struct {
	VideoID   uuid.UUID   `json:"video_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	Score     float64     `json:"score"`
}

// Hacker-News-style gravity: views / (hours_since_published + 2)^1.5. Same
// language is preferred first (language-aware) without excluding other langs.
func (q *Queries) HomeTrending(ctx context.Context, arg HomeTrendingParams) ([]HomeTrendingRow, error) {
	rows, err := q.db.Query(ctx, homeTrending,
		arg.HideSensitive,
		arg.Exclude,
		arg.Language,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeTrendingRow
	for rows.Next() {
		var i HomeTrendingRow
		if err := rows.Scan(&i.VideoID, &i.ChannelID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleByIDs = `-- name: ListEligibleByIDs :many
SELECT d.video_id, d.channel_id
FROM search.documents d
WHERE d.eligible
  AND (NOT $1::bool OR NOT d.is_sensitive)
  AND d.video_id = ANY($2::uuid[])
`

type ListEligibleByIDsParams struct {
	HideSensitive bool        `json:"hide_sensitive"`
	Ids           []uuid.UUID `json:"ids"`
}

type ListEligibleByIDsRow struct {
	VideoID   uuid.UUID   `json:"video_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

// Fetch the eligible (and, when requested, non-sensitive) documents among a set
// of ids — used to filter the gated Redis trending list before it feeds the home
// feed. Order is not preserved here; the caller re-imposes the trending order.
func (q *Queries) ListEligibleByIDs(ctx context.Context, arg ListEligibleByIDsParams) ([]ListEligibleByIDsRow, error) {
	rows, err := q.db.Query(ctx, listEligibleByIDs, arg.HideSensitive, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleByIDsRow
	for rows.Next() {
		var i ListEligibleByIDsRow
		if err := rows.Scan(&i.VideoID, &i.ChannelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const popularEligible = `-- name: PopularEligible :many
SELECT d.video_id, d.channel_id
FROM search.documents d
WHERE d.eligible
  AND (NOT $1::bool OR NOT d.is_sensitive)
  AND ($2::uuid[] IS NULL OR d.video_id <> ALL($2::uuid[]))
ORDER BY d.views DESC, d.published_at DESC NULLS LAST, d.video_id
LIMIT $3::int
`

type PopularEligibleParams struct {
	HideSensitive bool        `json:"hide_sensitive"`
	Exclude       []uuid.UUID `json:"exclude"`
	Lim           int32       `json:"lim"`
}

type PopularEligibleRow struct {
	VideoID   uuid.UUID   `json:"video_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

// Top eligible videos by views, excluding a caller-supplied set (self + picks).
func (q *Queries) PopularEligible(ctx context.Context, arg PopularEligibleParams) ([]PopularEligibleRow, error) {
	rows, err := q.db.Query(ctx, popularEligible, arg.HideSensitive, arg.Exclude, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PopularEligibleRow
	for rows.Next() {
		var i PopularEligibleRow
		if err := rows.Scan(&i.VideoID, &i.ChannelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relatedByOverlap = `-- name: RelatedByOverlap :many
SELECT d.video_id, d.channel_id,
    ( (CASE WHEN d.category IS NOT NULL AND d.category = $1 THEN 1 ELSE 0 END)
    + (CASE WHEN d.language IS NOT NULL AND d.language = $2 THEN 1 ELSE 0 END)
    + cardinality(ARRAY(SELECT unnest(d.tags) INTERSECT SELECT unnest($3::text[])))
    )::int AS overlap
FROM search.documents d
WHERE d.eligible
  AND (NOT $4::bool OR NOT d.is_sensitive)
  AND d.video_id <> $5
  AND (
        d.category = $1
     OR d.language = $2
     OR d.tags && $3::text[]
      )
ORDER BY overlap DESC, d.views DESC, d.published_at DESC NULLS LAST, d.video_id
LIMIT $6::int
`

type RelatedByOverlapParams struct {
	Category      *string   `json:"category"`
	Language      *string   `json:"language"`
	Tags          []string  `json:"tags"`
	HideSensitive bool      `json:"hide_sensitive"`
	VideoID       uuid.UUID `json:"video_id"`
	Lim           int32     `json:"lim"`
}

type RelatedByOverlapRow struct {
	VideoID   uuid.UUID   `json:"video_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	Overlap   int32       `json:"overlap"`
}

// Videos sharing tags/category/language with the seed, scored by overlap size.
func (q *Queries) RelatedByOverlap(ctx context.Context, arg RelatedByOverlapParams) ([]RelatedByOverlapRow, error) {
	rows, err := q.db.Query(ctx, relatedByOverlap,
		arg.Category,
		arg.Language,
		arg.Tags,
		arg.HideSensitive,
		arg.VideoID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelatedByOverlapRow
	for rows.Next() {
		var i RelatedByOverlapRow
		if err := rows.Scan(&i.VideoID, &i.ChannelID, &i.Overlap); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relatedSameChannel = `-- name: RelatedSameChannel :many
SELECT d.video_id, d.channel_id
FROM search.documents d
WHERE d.eligible
  AND (NOT $1::bool OR NOT d.is_sensitive)
  AND d.channel_id = $2
  AND d.video_id <> $3
ORDER BY d.published_at DESC NULLS LAST, d.video_id
LIMIT $4::int
`

type RelatedSameChannelParams struct {
	HideSensitive bool        `json:"hide_sensitive"`
	ChannelID     pgtype.UUID `json:"channel_id"`
	VideoID       uuid.UUID   `json:"video_id"`
	Lim           int32       `json:"lim"`
}

type RelatedSameChannelRow struct {
	VideoID   uuid.UUID   `json:"video_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

// Most recent other videos from the same channel (related "similar" seed).
func (q *Queries) RelatedSameChannel(ctx context.Context, arg RelatedSameChannelParams) ([]RelatedSameChannelRow, error) {
	rows, err := q.db.Query(ctx, relatedSameChannel,
		arg.HideSensitive,
		arg.ChannelID,
		arg.VideoID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelatedSameChannelRow
	for rows.Next() {
		var i RelatedSameChannelRow
		if err := rows.Scan(&i.VideoID, &i.ChannelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
