// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reevaluation.sql

package sqlcgen

import (
	"context"
	"time"
)

const previewSuggestibleReevaluation = `-- name: PreviewSuggestibleReevaluation :many
WITH survivors AS (
    -- Exact distinct users over the retained window, mirroring rollups.sql:
    -- count(DISTINCT user_id) ignores NULLs, anonymous rows fall back to their
    -- distinct session_id.
    SELECT ql.normalized_query,
           (count(DISTINCT ql.user_id)
              + count(DISTINCT CASE WHEN ql.user_id IS NULL THEN ql.session_id END))::int AS distinct_users
    FROM search.query_log ql
    WHERE ql.submitted_at >= $4 AND ql.normalized_query <> ''
    GROUP BY ql.normalized_query
)
SELECT qa.normalized_query,
       COALESCE(s.distinct_users, 0)::int AS distinct_users,
       (((COALESCE(s.distinct_users, 0) >= $1::int) AND NOT qa.banned))::bool AS suggestible
FROM search.query_aggregates qa
LEFT JOIN survivors s ON s.normalized_query = qa.normalized_query
WHERE qa.normalized_query > $2
  AND ((COALESCE(s.distinct_users, 0) >= $1::int) AND NOT qa.banned)
      IS DISTINCT FROM qa.suggestible
ORDER BY qa.normalized_query
LIMIT $3::int
`

type PreviewSuggestibleReevaluationParams struct {
	MinUsers    int32     `json:"min_users"`
	After       string    `json:"after"`
	Lim         int32     `json:"lim"`
	WindowStart time.Time `json:"window_start"`
}

type PreviewSuggestibleReevaluationRow struct {
	NormalizedQuery string `json:"normalized_query"`
	DistinctUsers   int32  `json:"distinct_users"`
	Suggestible     bool   `json:"suggestible"`
}

// The dry run. Returns the rows the pass WOULD move and the value each would
// take, changing nothing, so an operator can measure the blast radius before
// taking it — a remediation that silently empties autosuggest is a worse outcome
// than the bug it closes. Keyset-paged on the primary key (@after) rather than
// OFFSET so a full count over a large table is a bounded forward sweep.
func (q *Queries) PreviewSuggestibleReevaluation(ctx context.Context, arg PreviewSuggestibleReevaluationParams) ([]PreviewSuggestibleReevaluationRow, error) {
	rows, err := q.db.Query(ctx, previewSuggestibleReevaluation,
		arg.MinUsers,
		arg.After,
		arg.Lim,
		arg.WindowStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreviewSuggestibleReevaluationRow
	for rows.Next() {
		var i PreviewSuggestibleReevaluationRow
		if err := rows.Scan(&i.NormalizedQuery, &i.DistinctUsers, &i.Suggestible); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryLogHasRowsInWindow = `-- name: QueryLogHasRowsInWindow :one

SELECT EXISTS (
    SELECT 1 FROM search.query_log
    WHERE submitted_at >= $1 AND normalized_query <> ''
)::bool AS has_rows
`

// Suggestible re-evaluation: recompute search.query_aggregates.suggestible for
// EVERY aggregate row from the currently-surviving query_log, not only for rows
// carrying new traffic.
//
// Why this exists. RollupQueryAggregates recomputes `suggestible` only for
// queries present in its `batch` CTE, and that CTE is INNER JOINed — a query
// receiving no new traffic is never revisited. Nothing else writes the flag
// (moderation.sql aside) and no DELETE in the schema touches query_aggregates:
// retention prunes query_log and behavior_events only. So a string that once
// cleared the distinct-user floor stayed suggestible forever, and at the
// retention boundary the query_log rows proving how it got there were deleted
// while the suggestion survived. These queries make `suggestible` mean
// "currently supported by surviving evidence" instead of "once was".
//
// The predicate below is deliberately the SAME predicate rollups.sql applies
// (`distinct_users >= min_users AND NOT banned`, counted over the same retention
// window with the same anonymous session fallback). This pass is the rollup's
// recount with the INNER JOIN removed — not a second, competing policy — so the
// two can never disagree and the flag cannot flap between them.
// Reconcile-orphan guard. This repo already learned that a repair pass which
// runs on incomplete data damages the index; an empty retention window is that
// signature exactly. With no surviving rows every aggregate would recount to
// zero and the pass would un-suggest the entire instance in one sweep — so the
// caller refuses to run. EXISTS, not count(*): it stops at the first row.
func (q *Queries) QueryLogHasRowsInWindow(ctx context.Context, windowStart time.Time) (bool, error) {
	row := q.db.QueryRow(ctx, queryLogHasRowsInWindow, windowStart)
	var has_rows bool
	err := row.Scan(&has_rows)
	return has_rows, err
}

const reevaluateSuggestible = `-- name: ReevaluateSuggestible :execrows
WITH survivors AS (
    SELECT ql.normalized_query,
           (count(DISTINCT ql.user_id)
              + count(DISTINCT CASE WHEN ql.user_id IS NULL THEN ql.session_id END))::int AS distinct_users
    FROM search.query_log ql
    WHERE ql.submitted_at >= $1 AND ql.normalized_query <> ''
    GROUP BY ql.normalized_query
),
changed AS (
    SELECT qa.normalized_query,
           COALESCE(s.distinct_users, 0)::int AS distinct_users,
           ((COALESCE(s.distinct_users, 0) >= $2::int) AND NOT qa.banned) AS want
    FROM search.query_aggregates qa
    LEFT JOIN survivors s ON s.normalized_query = qa.normalized_query
    WHERE ((COALESCE(s.distinct_users, 0) >= $2::int) AND NOT qa.banned)
          IS DISTINCT FROM qa.suggestible
    ORDER BY qa.normalized_query
    LIMIT $3::int
)
UPDATE search.query_aggregates qa
SET suggestible    = c.want,
    distinct_users = c.distinct_users
FROM changed c
WHERE qa.normalized_query = c.normalized_query
`

type ReevaluateSuggestibleParams struct {
	WindowStart time.Time `json:"window_start"`
	MinUsers    int32     `json:"min_users"`
	Lim         int32     `json:"lim"`
}

// Apply one bounded batch, in the house `:execrows` idiom the prune queries use.
//
// Two properties make the caller's loop safe. (1) The `changed` CTE selects ONLY
// rows whose flag actually moves, so every batch strictly shrinks the remaining
// work and the loop converges without a cursor — a row it fixes cannot reappear.
// (2) `banned` is absent from the SET list, so the pass cannot clear a ban: it is
// structurally incapable of un-banning, not merely careful not to. A banned row's
// `want` is false by construction, so it is driven to (and held at)
// suggestible = false no matter how much traffic it receives.
//
// distinct_users moves with the flag rather than being left at the rollup's stale
// high-water mark: a row reading "not suggestible, 3 distinct users" would look
// like a bug on the operator surface instead of like the evidence it is.
func (q *Queries) ReevaluateSuggestible(ctx context.Context, arg ReevaluateSuggestibleParams) (int64, error) {
	result, err := q.db.Exec(ctx, reevaluateSuggestible, arg.WindowStart, arg.MinUsers, arg.Lim)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
