// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollups.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldBehaviorEvents = `-- name: DeleteOldBehaviorEvents :execrows
DELETE FROM search.behavior_events WHERE occurred_at < now() - make_interval(days => $1::int)
`

func (q *Queries) DeleteOldBehaviorEvents(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldBehaviorEvents, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldQueryLog = `-- name: DeleteOldQueryLog :execrows
DELETE FROM search.query_log WHERE submitted_at < now() - make_interval(days => $1::int)
`

func (q *Queries) DeleteOldQueryLog(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldQueryLog, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deriveMeaningfulWatch = `-- name: DeriveMeaningfulWatch :many
INSERT INTO search.behavior_events
    (event_id, type, user_id, session_id, normalized_query, video_id, occurred_at, props)
SELECT
    uuid_generate_v5('6ba7b814-9dad-11d1-80b4-00c04fd430c8'::uuid,
        'mw|' || COALESCE(wp.user_id::text, wp.session_id, 'anon') || '|' || wp.video_id::text
             || '|' || to_char(wp.occurred_at AT TIME ZONE 'UTC', 'YYYYMMDD')),
    'video.meaningful_watch',
    wp.user_id, wp.session_id,
    (SELECT be.normalized_query FROM search.behavior_events be
      WHERE be.session_id IS NOT DISTINCT FROM wp.session_id
        AND be.video_id = wp.video_id
        AND be.type IN ('search.result_clicked', 'video.play_started')
        AND be.normalized_query IS NOT NULL
        AND be.occurred_at <= wp.occurred_at
      ORDER BY be.occurred_at DESC LIMIT 1),
    wp.video_id, wp.occurred_at,
    jsonb_build_object('allow_history', COALESCE((wp.props->>'allow_history')::boolean, false),
                       'derived_from', 'watch_progress')
FROM search.behavior_events wp
WHERE wp.type = 'video.watch_progress'
  AND wp.id > $1 AND wp.id <= $2
  AND wp.video_id IS NOT NULL
  AND (
        COALESCE((wp.props->>'position_seconds')::double precision, 0) >= $3::double precision
     OR ( (wp.props->>'duration_seconds') IS NOT NULL
          AND (wp.props->>'duration_seconds')::double precision > 0
          AND COALESCE((wp.props->>'position_seconds')::double precision, 0)
                >= (wp.props->>'duration_seconds')::double precision * $4::double precision )
      )
ON CONFLICT (event_id) DO NOTHING
RETURNING event_id, user_id, session_id, video_id, normalized_query, props
`

type DeriveMeaningfulWatchParams struct {
	Cursor     int64   `json:"cursor"`
	Maxid      int64   `json:"maxid"`
	MwSeconds  float64 `json:"mw_seconds"`
	MwFraction float64 `json:"mw_fraction"`
}

type DeriveMeaningfulWatchRow struct {
	EventID         uuid.UUID   `json:"event_id"`
	UserID          pgtype.UUID `json:"user_id"`
	SessionID       *string     `json:"session_id"`
	VideoID         pgtype.UUID `json:"video_id"`
	NormalizedQuery *string     `json:"normalized_query"`
	Props           []byte      `json:"props"`
}

// Derive synthetic video.meaningful_watch rows from qualifying video.watch_progress
// events (position >= mw_seconds OR >= mw_pct% of duration). The event_id is a
// deterministic uuid_generate_v5 over (subject, video, day) so re-derivation is a
// no-op. The query is attributed to the latest search-context query for that
// (session, video). Returns only the rows actually inserted so the worker can
// apply the watch-projection weight and trend:v bump exactly once.
func (q *Queries) DeriveMeaningfulWatch(ctx context.Context, arg DeriveMeaningfulWatchParams) ([]DeriveMeaningfulWatchRow, error) {
	rows, err := q.db.Query(ctx, deriveMeaningfulWatch,
		arg.Cursor,
		arg.Maxid,
		arg.MwSeconds,
		arg.MwFraction,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeriveMeaningfulWatchRow
	for rows.Next() {
		var i DeriveMeaningfulWatchRow
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.SessionID,
			&i.VideoID,
			&i.NormalizedQuery,
			&i.Props,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const foldEngagement = `-- name: FoldEngagement :exec
INSERT INTO search.query_video_engagement
    (normalized_query, video_id, impressions, clicks, meaningful_watches, updated_at)
SELECT be.normalized_query, be.video_id,
       count(*) FILTER (WHERE be.type = 'video.impression'),
       count(*) FILTER (WHERE be.type = 'search.result_clicked'),
       count(*) FILTER (WHERE be.type = 'video.meaningful_watch'),
       now()
FROM search.behavior_events be
WHERE be.id > $1 AND be.id <= $2
  AND be.normalized_query IS NOT NULL
  AND be.video_id IS NOT NULL
  AND be.type IN ('video.impression', 'search.result_clicked', 'video.meaningful_watch')
GROUP BY be.normalized_query, be.video_id
ON CONFLICT (normalized_query, video_id) DO UPDATE SET
    impressions        = search.query_video_engagement.impressions + EXCLUDED.impressions,
    clicks             = search.query_video_engagement.clicks + EXCLUDED.clicks,
    meaningful_watches = search.query_video_engagement.meaningful_watches + EXCLUDED.meaningful_watches,
    updated_at         = now()
`

type FoldEngagementParams struct {
	Cursor int64 `json:"cursor"`
	Maxid  int64 `json:"maxid"`
}

// Fold new behavior_events (id in (cursor, maxid]) into per-(query,video)
// engagement counters. Meaningful-watch rows derived in the current pass have
// id > maxid, so they are folded on the next pass — counted exactly once.
func (q *Queries) FoldEngagement(ctx context.Context, arg FoldEngagementParams) error {
	_, err := q.db.Exec(ctx, foldEngagement, arg.Cursor, arg.Maxid)
	return err
}

const getWorkerCursor = `-- name: GetWorkerCursor :one

SELECT cursor_pos FROM search.worker_cursors WHERE cursor_name = $1
`

// Worker queries (W2): cursors, aggregate/engagement rollups, meaningful-watch
// derivation, sessionizer reads, and retention.
func (q *Queries) GetWorkerCursor(ctx context.Context, cursorName string) (int64, error) {
	row := q.db.QueryRow(ctx, getWorkerCursor, cursorName)
	var cursor_pos int64
	err := row.Scan(&cursor_pos)
	return cursor_pos, err
}

const insertDerivedBehaviorEvent = `-- name: InsertDerivedBehaviorEvent :one
INSERT INTO search.behavior_events
    (event_id, type, user_id, session_id, normalized_query, video_id, occurred_at, props)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (event_id) DO NOTHING
RETURNING event_id
`

type InsertDerivedBehaviorEventParams struct {
	EventID         uuid.UUID   `json:"event_id"`
	Type            string      `json:"type"`
	UserID          pgtype.UUID `json:"user_id"`
	SessionID       *string     `json:"session_id"`
	NormalizedQuery *string     `json:"normalized_query"`
	VideoID         pgtype.UUID `json:"video_id"`
	OccurredAt      time.Time   `json:"occurred_at"`
	Props           []byte      `json:"props"`
}

// Insert one worker-derived behavior event (reformulated/abandoned), deduped on
// its deterministic event_id. Returns the id only on a fresh insert.
func (q *Queries) InsertDerivedBehaviorEvent(ctx context.Context, arg InsertDerivedBehaviorEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertDerivedBehaviorEvent,
		arg.EventID,
		arg.Type,
		arg.UserID,
		arg.SessionID,
		arg.NormalizedQuery,
		arg.VideoID,
		arg.OccurredAt,
		arg.Props,
	)
	var event_id uuid.UUID
	err := row.Scan(&event_id)
	return event_id, err
}

const lastReconcileEndAgeSeconds = `-- name: LastReconcileEndAgeSeconds :one
SELECT COALESCE(EXTRACT(EPOCH FROM (now() - max(received_at))), -1)::double precision
FROM search.events_inbox WHERE type = 'reconcile.end'
`

// Seconds since the most recent reconcile.end was received, or -1 if none is on
// record (the events_inbox row may have been pruned after 7d — already far past
// the staleness threshold).
func (q *Queries) LastReconcileEndAgeSeconds(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, lastReconcileEndAgeSeconds)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const listEngagementSignals = `-- name: ListEngagementSignals :many
SELECT session_id, normalized_query, type, occurred_at
FROM search.behavior_events
WHERE type IN ('search.result_clicked', 'video.play_started')
  AND session_id IS NOT NULL
  AND occurred_at >= $1 AND occurred_at <= $2
`

type ListEngagementSignalsParams struct {
	FromTs time.Time `json:"from_ts"`
	ToTs   time.Time `json:"to_ts"`
}

type ListEngagementSignalsRow struct {
	SessionID       *string   `json:"session_id"`
	NormalizedQuery *string   `json:"normalized_query"`
	Type            string    `json:"type"`
	OccurredAt      time.Time `json:"occurred_at"`
}

// Click/play signals used to decide whether a query was abandoned, bounded to the
// sessionizer batch's time window.
func (q *Queries) ListEngagementSignals(ctx context.Context, arg ListEngagementSignalsParams) ([]ListEngagementSignalsRow, error) {
	rows, err := q.db.Query(ctx, listEngagementSignals, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEngagementSignalsRow
	for rows.Next() {
		var i ListEngagementSignalsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.NormalizedQuery,
			&i.Type,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueryLogRange = `-- name: ListQueryLogRange :many
SELECT id, normalized_query, display_query, user_id, session_id, submitted_at
FROM search.query_log
WHERE id > $1 AND id <= $2 AND session_id IS NOT NULL
ORDER BY session_id, submitted_at, id
`

type ListQueryLogRangeParams struct {
	Cursor int64 `json:"cursor"`
	Maxid  int64 `json:"maxid"`
}

type ListQueryLogRangeRow struct {
	ID              int64       `json:"id"`
	NormalizedQuery string      `json:"normalized_query"`
	DisplayQuery    string      `json:"display_query"`
	UserID          pgtype.UUID `json:"user_id"`
	SessionID       *string     `json:"session_id"`
	SubmittedAt     time.Time   `json:"submitted_at"`
}

// Settled query_log rows in the sessionizer's cursor range (session-scoped only),
// ordered so a session's queries are contiguous and time-ordered.
func (q *Queries) ListQueryLogRange(ctx context.Context, arg ListQueryLogRangeParams) ([]ListQueryLogRangeRow, error) {
	rows, err := q.db.Query(ctx, listQueryLogRange, arg.Cursor, arg.Maxid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQueryLogRangeRow
	for rows.Next() {
		var i ListQueryLogRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.NormalizedQuery,
			&i.DisplayQuery,
			&i.UserID,
			&i.SessionID,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxBehaviorEventID = `-- name: MaxBehaviorEventID :one
SELECT COALESCE(max(id), 0)::bigint FROM search.behavior_events
`

func (q *Queries) MaxBehaviorEventID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, maxBehaviorEventID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const maxQueryLogID = `-- name: MaxQueryLogID :one
SELECT COALESCE(max(id), 0)::bigint FROM search.query_log
`

func (q *Queries) MaxQueryLogID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, maxQueryLogID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const maxSettledQueryLogID = `-- name: MaxSettledQueryLogID :one
SELECT COALESCE(max(id), 0)::bigint FROM search.query_log WHERE submitted_at <= $1
`

// Highest query_log id whose abandonment/reformulation window has closed. Because
// id and submitted_at rise together, this is a clean high-water mark below which
// every row is settled.
func (q *Queries) MaxSettledQueryLogID(ctx context.Context, cutoff time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, maxSettledQueryLogID, cutoff)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneEventsInbox = `-- name: PruneEventsInbox :execrows
DELETE FROM search.events_inbox WHERE received_at < now() - make_interval(days => $1::int)
`

func (q *Queries) PruneEventsInbox(ctx context.Context, days int32) (int64, error) {
	result, err := q.db.Exec(ctx, pruneEventsInbox, days)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneWatchProjection = `-- name: PruneWatchProjection :execrows
DELETE FROM search.user_watch_projection
WHERE weight * power(2, - GREATEST(0, EXTRACT(EPOCH FROM (now() - last_watched_at)))
                        / (3600.0 * $1::double precision)) < $2::double precision
`

type PruneWatchProjectionParams struct {
	HalfLifeHours float64 `json:"half_life_hours"`
	Floor         float64 `json:"floor"`
}

// Drop projection rows whose decayed weight has fallen below a floor.
func (q *Queries) PruneWatchProjection(ctx context.Context, arg PruneWatchProjectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneWatchProjection, arg.HalfLifeHours, arg.Floor)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rollupQueryAggregates = `-- name: RollupQueryAggregates :exec
WITH batch AS (
    SELECT ql.normalized_query,
           count(*)             AS delta,
           min(ql.submitted_at) AS batch_first_seen,
           max(ql.submitted_at) AS batch_last_seen
    FROM search.query_log ql
    WHERE ql.id > $3 AND ql.id <= $4 AND ql.normalized_query <> ''
    GROUP BY ql.normalized_query
),
recount AS (
    -- Exact distinct users: count(DISTINCT user_id) ignores NULLs automatically;
    -- anonymous rows fall back to their distinct session_id. FILTER is avoided
    -- deliberately (it trips sqlc 1.31.1's named-parameter editor here).
    SELECT b.normalized_query,
           (count(DISTINCT ql.user_id)
              + count(DISTINCT CASE WHEN ql.user_id IS NULL THEN ql.session_id END))::int AS distinct_users
    FROM batch b
    JOIN search.query_log ql ON ql.normalized_query = b.normalized_query
        AND ql.submitted_at >= $5
    GROUP BY b.normalized_query
),
display AS (
    SELECT DISTINCT ON (ql.normalized_query) ql.normalized_query, ql.display_query
    FROM search.query_log ql
    JOIN batch b ON b.normalized_query = ql.normalized_query
    ORDER BY ql.normalized_query, ql.submitted_at DESC, ql.id DESC
)
INSERT INTO search.query_aggregates
    (normalized_query, display_query, total_count, distinct_users, decayed_freq, first_seen, last_seen, suggestible, banned)
SELECT b.normalized_query,
       d.display_query,
       COALESCE(qa.total_count, 0) + b.delta,
       r.distinct_users,
       COALESCE(qa.decayed_freq, 0)
           * power(2, - (CASE WHEN qa.last_seen IS NULL THEN 0
                              ELSE GREATEST(0, EXTRACT(EPOCH FROM (b.batch_last_seen - qa.last_seen))) END)
                        / $1::double precision)
           + b.delta::double precision,
       LEAST(qa.first_seen, b.batch_first_seen),
       GREATEST(qa.last_seen, b.batch_last_seen),
       (r.distinct_users >= $2::int) AND NOT COALESCE(qa.banned, false),
       COALESCE(qa.banned, false)
FROM batch b
JOIN recount r ON r.normalized_query = b.normalized_query
JOIN display d ON d.normalized_query = b.normalized_query
LEFT JOIN search.query_aggregates qa ON qa.normalized_query = b.normalized_query
ON CONFLICT (normalized_query) DO UPDATE SET
    display_query  = EXCLUDED.display_query,
    total_count    = EXCLUDED.total_count,
    distinct_users = EXCLUDED.distinct_users,
    decayed_freq   = EXCLUDED.decayed_freq,
    first_seen     = EXCLUDED.first_seen,
    last_seen      = EXCLUDED.last_seen,
    suggestible    = EXCLUDED.suggestible,
    banned         = EXCLUDED.banned
`

type RollupQueryAggregatesParams struct {
	HalfLifeSeconds float64   `json:"half_life_seconds"`
	MinUsers        int32     `json:"min_users"`
	FromID          int64     `json:"from_id"`
	Maxid           int64     `json:"maxid"`
	WindowStart     time.Time `json:"window_start"`
}

// Fold new query_log rows (id in (cursor, maxid]) into query_aggregates.
// decayed_freq is decay-then-increment (half-life from config); distinct_users is
// an EXACT recount over the retained window (distinct user_id + session fallback);
// display_query is the most recent display form; suggestible clears the min
// distinct-user threshold and is never true for a banned query.
// The full new row (including the decayed_freq computed from the LEFT-JOINed
// existing aggregate) is built in the SELECT, so the ON CONFLICT clause is a
// trivial column-wise overwrite. The aggregates_rollup worker is a single writer
// inside one transaction, so the read-compute-upsert is race-free.
func (q *Queries) RollupQueryAggregates(ctx context.Context, arg RollupQueryAggregatesParams) error {
	_, err := q.db.Exec(ctx, rollupQueryAggregates,
		arg.HalfLifeSeconds,
		arg.MinUsers,
		arg.FromID,
		arg.Maxid,
		arg.WindowStart,
	)
	return err
}

const setWorkerCursor = `-- name: SetWorkerCursor :exec
INSERT INTO search.worker_cursors (cursor_name, cursor_pos, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (cursor_name) DO UPDATE SET cursor_pos = EXCLUDED.cursor_pos, updated_at = now()
`

type SetWorkerCursorParams struct {
	CursorName string `json:"cursor_name"`
	CursorPos  int64  `json:"cursor_pos"`
}

func (q *Queries) SetWorkerCursor(ctx context.Context, arg SetWorkerCursorParams) error {
	_, err := q.db.Exec(ctx, setWorkerCursor, arg.CursorName, arg.CursorPos)
	return err
}
