// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const searchSimple = `-- name: SearchSimple :many
WITH q AS (
    SELECT websearch_to_tsquery('simple', $1::text) AS tsq
)
SELECT d.video_id,
    ( 0.5 * ts_rank_cd(d.tsv, q.tsq)
    + 0.2 * COALESCE(similarity(lower(d.title), $1::text), 0)
    + 0.1 * (
        (CASE WHEN lower(d.title) = $1::text THEN 1.0 ELSE 0.0 END)
      + (CASE WHEN lower(coalesce(d.channel_name, '')) = $1::text THEN 0.5 ELSE 0.0 END)
      + (CASE WHEN $1::text = ANY(SELECT lower(x) FROM unnest(d.tags) AS x) THEN 0.5 ELSE 0.0 END)
      )
    + 0.1 * (ln(1 + d.views) / 20.0)
    + 0.1 * exp(-ln(2) * (EXTRACT(EPOCH FROM (now() - COALESCE(d.published_at, d.source_updated_at))) / 2592000.0))
    )::double precision AS score
FROM search.documents d, q
WHERE d.eligible
  AND (NOT $2::bool OR NOT d.is_sensitive)
  AND (
        d.tsv @@ q.tsq
     OR lower(d.title) % $1::text
     OR d.tags @> ARRAY[$1::text]
     OR lower(d.channel_name) = $1::text
      )
  AND ($3::text IS NULL OR $3 = ANY(d.tags))
  AND ($4::text IS NULL OR d.category = $4)
  AND ($5::text IS NULL OR d.language = $5)
  AND ($6::text IS NULL OR d.license = $6)
ORDER BY score DESC, d.published_at DESC NULLS LAST, d.video_id
LIMIT $8::int OFFSET $7::int
`

type SearchSimpleParams struct {
	Query         string  `json:"query"`
	HideSensitive bool    `json:"hide_sensitive"`
	Tag           *string `json:"tag"`
	Category      *string `json:"category"`
	Language      *string `json:"language"`
	License       *string `json:"license"`
	Off           int32   `json:"off"`
	Lim           int32   `json:"lim"`
}

type SearchSimpleRow struct {
	VideoID uuid.UUID `json:"video_id"`
	Score   float64   `json:"score"`
}

// Simple-mode hybrid search (§1.7). Candidate recall unions full-text
// (websearch_to_tsquery), trigram title similarity, and exact tag/channel
// matches; the score blends ts_rank_cd, trigram similarity, exact-match flags,
// log-normalized views, and a 30-day freshness half-life. Static eligibility +
// hide_sensitive + optional tag/category/language/license filters are applied
// in SQL.
// Order is fully deterministic: score DESC, then newest, then id.
func (q *Queries) SearchSimple(ctx context.Context, arg SearchSimpleParams) ([]SearchSimpleRow, error) {
	rows, err := q.db.Query(ctx, searchSimple,
		arg.Query,
		arg.HideSensitive,
		arg.Tag,
		arg.Category,
		arg.Language,
		arg.License,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSimpleRow
	for rows.Next() {
		var i SearchSimpleRow
		if err := rows.Scan(&i.VideoID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSimpleCount = `-- name: SearchSimpleCount :one
WITH q AS (
    SELECT websearch_to_tsquery('simple', $2::text) AS tsq
)
SELECT count(*)::bigint AS total
FROM search.documents d, q
WHERE d.eligible
  AND (NOT $1::bool OR NOT d.is_sensitive)
  AND (
        d.tsv @@ q.tsq
     OR lower(d.title) % $2::text
     OR d.tags @> ARRAY[$2::text]
     OR lower(d.channel_name) = $2::text
      )
  AND ($3::text IS NULL OR $3 = ANY(d.tags))
  AND ($4::text IS NULL OR d.category = $4)
  AND ($5::text IS NULL OR d.language = $5)
  AND ($6::text IS NULL OR d.license = $6)
`

type SearchSimpleCountParams struct {
	HideSensitive bool    `json:"hide_sensitive"`
	Query         string  `json:"query"`
	Tag           *string `json:"tag"`
	Category      *string `json:"category"`
	Language      *string `json:"language"`
	License       *string `json:"license"`
}

// Total hit count for simple-mode search: COUNT(*) over EXACTLY the predicates
// SearchSimple pages over, with no ORDER BY / LIMIT / OFFSET. The scoring
// expression is irrelevant to the count, so only the FROM + WHERE are shared —
// and they must stay byte-identical to SearchSimple's. A count whose predicates
// drift from the page query's is worse than no count at all, so edit the two
// WHERE clauses together; TestSearchCountSharesSimpleWherePredicates (internal/
// store) fails the build if they ever diverge.
func (q *Queries) SearchSimpleCount(ctx context.Context, arg SearchSimpleCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, searchSimpleCount,
		arg.HideSensitive,
		arg.Query,
		arg.Tag,
		arg.Category,
		arg.Language,
		arg.License,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}
