// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shadow.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const shadowImpressions = `-- name: ShadowImpressions :many

SELECT
    imp.session_id,
    imp.normalized_query,
    imp.video_id,
    COALESCE(imp.position, 0)::int AS position,
    imp.occurred_at,
    EXISTS (
        SELECT 1 FROM search.behavior_events c
        WHERE c.type = 'search.result_clicked'
          AND c.session_id IS NOT DISTINCT FROM imp.session_id
          AND c.normalized_query = imp.normalized_query
          AND c.video_id = imp.video_id
          AND c.occurred_at >= imp.occurred_at
    ) AS clicked,
    EXISTS (
        SELECT 1 FROM search.behavior_events m
        WHERE m.type = 'video.meaningful_watch'
          AND m.session_id IS NOT DISTINCT FROM imp.session_id
          AND m.video_id = imp.video_id
          AND m.occurred_at >= imp.occurred_at
    ) AS meaningful
FROM search.behavior_events imp
WHERE imp.type = 'video.impression'
  AND imp.normalized_query IS NOT NULL
  AND imp.video_id IS NOT NULL
  AND imp.occurred_at >= now() - make_interval(days => $1::int)
ORDER BY imp.session_id NULLS FIRST, imp.normalized_query, position, imp.video_id
`

type ShadowImpressionsRow struct {
	SessionID       *string     `json:"session_id"`
	NormalizedQuery *string     `json:"normalized_query"`
	VideoID         pgtype.UUID `json:"video_id"`
	Position        int32       `json:"position"`
	OccurredAt      time.Time   `json:"occurred_at"`
	Clicked         bool        `json:"clicked"`
	Meaningful      bool        `json:"meaningful"`
}

// Shadow evaluation (§1.9). Replays the last N days of logged impressions with
// their click / meaningful-watch labels so a shadow ranker can be scored offline
// (NDCG@10 / MRR@10) against the production ordering actually served and against
// a heuristic re-rank — with NO effect on live serving.
// One row per logged impression (video.impression) in the window, carrying the
// served position and whether that (session, query, video) was later clicked
// and/or meaningful-watched. Label derivation (documented in docs/evaluation.md):
// meaningful-watch ⇒ graded relevance 2, click ⇒ 1, neither ⇒ 0. Grouped by
// (session, query) into ranked impression lists in Go.
func (q *Queries) ShadowImpressions(ctx context.Context, days int32) ([]ShadowImpressionsRow, error) {
	rows, err := q.db.Query(ctx, shadowImpressions, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShadowImpressionsRow
	for rows.Next() {
		var i ShadowImpressionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.NormalizedQuery,
			&i.VideoID,
			&i.Position,
			&i.OccurredAt,
			&i.Clicked,
			&i.Meaningful,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
