// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suggestions.sql

package sqlcgen

import (
	"context"
)

const suggestChannelPrefix = `-- name: SuggestChannelPrefix :many
SELECT d.channel_name, min(d.channel_handle)::text AS channel_handle, max(d.views)::bigint AS views
FROM search.documents d
WHERE d.eligible
  AND (NOT $1::bool OR NOT d.is_sensitive)
  AND d.channel_name IS NOT NULL
  AND lower(d.channel_name) LIKE $2::text
GROUP BY d.channel_name
ORDER BY views DESC
LIMIT $3::int
`

type SuggestChannelPrefixParams struct {
	HideSensitive bool   `json:"hide_sensitive"`
	Prefix        string `json:"prefix"`
	Lim           int32  `json:"lim"`
}

type SuggestChannelPrefixRow struct {
	ChannelName   *string `json:"channel_name"`
	ChannelHandle string  `json:"channel_handle"`
	Views         int64   `json:"views"`
}

func (q *Queries) SuggestChannelPrefix(ctx context.Context, arg SuggestChannelPrefixParams) ([]SuggestChannelPrefixRow, error) {
	rows, err := q.db.Query(ctx, suggestChannelPrefix, arg.HideSensitive, arg.Prefix, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestChannelPrefixRow
	for rows.Next() {
		var i SuggestChannelPrefixRow
		if err := rows.Scan(&i.ChannelName, &i.ChannelHandle, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestTagPrefix = `-- name: SuggestTagPrefix :many
SELECT t::text AS tag, count(*)::bigint AS cnt
FROM search.documents d, unnest(d.tags) AS t
WHERE d.eligible
  AND (NOT $1::bool OR NOT d.is_sensitive)
  AND lower(t) LIKE $2::text
GROUP BY t
ORDER BY cnt DESC
LIMIT $3::int
`

type SuggestTagPrefixParams struct {
	HideSensitive bool   `json:"hide_sensitive"`
	Prefix        string `json:"prefix"`
	Lim           int32  `json:"lim"`
}

type SuggestTagPrefixRow struct {
	Tag string `json:"tag"`
	Cnt int64  `json:"cnt"`
}

func (q *Queries) SuggestTagPrefix(ctx context.Context, arg SuggestTagPrefixParams) ([]SuggestTagPrefixRow, error) {
	rows, err := q.db.Query(ctx, suggestTagPrefix, arg.HideSensitive, arg.Prefix, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestTagPrefixRow
	for rows.Next() {
		var i SuggestTagPrefixRow
		if err := rows.Scan(&i.Tag, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestTitleFuzzy = `-- name: SuggestTitleFuzzy :many
SELECT DISTINCT ON (lower(d.title)) d.title,
       similarity(lower(d.title), $1::text)::real AS sim,
       d.views
FROM search.documents d
WHERE d.eligible
  AND (NOT $2::bool OR NOT d.is_sensitive)
  AND similarity(lower(d.title), $1::text) >= 0.35
ORDER BY lower(d.title), sim DESC
LIMIT $3::int
`

type SuggestTitleFuzzyParams struct {
	Q             string `json:"q"`
	HideSensitive bool   `json:"hide_sensitive"`
	Lim           int32  `json:"lim"`
}

type SuggestTitleFuzzyRow struct {
	Title string  `json:"title"`
	Sim   float32 `json:"sim"`
	Views int64   `json:"views"`
}

// Typo fallback: trigram-similar titles, used only when exact-prefix results are
// short of the requested limit. Threshold 0.35 (algorithms report).
func (q *Queries) SuggestTitleFuzzy(ctx context.Context, arg SuggestTitleFuzzyParams) ([]SuggestTitleFuzzyRow, error) {
	rows, err := q.db.Query(ctx, suggestTitleFuzzy, arg.Q, arg.HideSensitive, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestTitleFuzzyRow
	for rows.Next() {
		var i SuggestTitleFuzzyRow
		if err := rows.Scan(&i.Title, &i.Sim, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestTitlePrefix = `-- name: SuggestTitlePrefix :many
SELECT DISTINCT ON (lower(d.title)) d.title, d.views
FROM search.documents d
WHERE d.eligible
  AND (NOT $1::bool OR NOT d.is_sensitive)
  AND lower(d.title) LIKE $2::text
ORDER BY lower(d.title), d.views DESC
LIMIT $3::int
`

type SuggestTitlePrefixParams struct {
	HideSensitive bool   `json:"hide_sensitive"`
	Prefix        string `json:"prefix"`
	Lim           int32  `json:"lim"`
}

type SuggestTitlePrefixRow struct {
	Title string `json:"title"`
	Views int64  `json:"views"`
}

// Doc-derived completions: distinct eligible titles whose lowercase form starts
// with the (already normalized) prefix. Uses the lower(title) text_pattern_ops
// index. @prefix must be the normalized prefix with a trailing '%'.
func (q *Queries) SuggestTitlePrefix(ctx context.Context, arg SuggestTitlePrefixParams) ([]SuggestTitlePrefixRow, error) {
	rows, err := q.db.Query(ctx, suggestTitlePrefix, arg.HideSensitive, arg.Prefix, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestTitlePrefixRow
	for rows.Next() {
		var i SuggestTitlePrefixRow
		if err := rows.Scan(&i.Title, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
